In [25]:
import networkx as nx
from igraph import Graph
import pandas as pd
from funciones import filtrar_triangulos, mostrar_look

## 1. CARGAR EL GRAFO Y LOS DATOS

In [26]:
G = nx.read_gml("../Modelos/graph.gml")

In [27]:
df_grafo = pd.read_csv("../Datos/Transformados/df_grafo_final.csv")
df_expandido = pd.read_csv("../Datos/Transformados/df_expandido.csv",sep=';')

## 2. ANÁLISIS DEL GRAFO

### Número de nodos

In [28]:
G.number_of_nodes()

2031

### Número de aristas

In [29]:
G.number_of_edges()

313557

### Nodos aislados

In [30]:
nodos_aislados = list(nx.isolates(G))
len(nodos_aislados)

0

### Centralidad de grado

In [31]:
dict(sorted(nx.degree_centrality(G).items(), key=lambda item: item[1], reverse=True))

{'22': 0.7413793103448275,
 '163': 0.7172413793103448,
 '401': 0.6945812807881773,
 '586': 0.6901477832512315,
 '813': 0.6763546798029556,
 '956': 0.654679802955665,
 '937': 0.6532019704433497,
 '954': 0.6507389162561575,
 '84': 0.6221674876847291,
 '493': 0.5778325123152709,
 '1507': 0.5768472906403941,
 '1922': 0.5724137931034482,
 '1923': 0.5724137931034482,
 '1343': 0.5315270935960591,
 '1344': 0.5315270935960591,
 '5': 0.5231527093596059,
 '4': 0.5108374384236453,
 '155': 0.5044334975369458,
 '783': 0.5044334975369458,
 '1618': 0.5004926108374383,
 '587': 0.49999999999999994,
 '967': 0.48226600985221674,
 '1259': 0.48226600985221674,
 '1011': 0.47980295566502457,
 '1163': 0.47931034482758617,
 '1164': 0.47931034482758617,
 '1158': 0.4778325123152709,
 '1876': 0.4778325123152709,
 '162': 0.47389162561576353,
 '1101': 0.4699507389162561,
 '1506': 0.46798029556650245,
 '1503': 0.467487684729064,
 '1753': 0.46650246305418713,
 '1751': 0.46600985221674873,
 '1617': 0.46551724137931033,
 '1680': 0.46551724137931033,
 '1338': 0.46206896551724136,
 '52': 0.46059113300492605,
 '59': 0.4591133004926108,
 '1543': 0.4591133004926108,
 '1544': 0.4591133004926108,
 '1756': 0.4591133004926108,
 '1584': 0.4586206896551724,
 '399': 0.45812807881773393,
 '1652': 0.45665024630541867,
 '1653': 0.45665024630541867,
 '1662': 0.45665024630541867,
 '1663': 0.45665024630541867,
 '1749': 0.454679802955665,
 '1937': 0.4532019704433497,
 '230': 0.4497536945812807,
 '297': 0.4467980295566502,
 '315': 0.44581280788177335,
 '316': 0.44581280788177335,
 '319': 0.44532019704433495,
 '957': 0.4443349753694581,
 '1345': 0.44334975369458124,
 '205': 0.44285714285714284,
 '82': 0.441871921182266,
 '65': 0.4408866995073891,
 '1927': 0.4359605911330049,
 '612': 0.42857142857142855,
 '441': 0.4270935960591133,
 '785': 0.42610837438423643,
 '85': 0.41625615763546797,
 '806': 0.41625615763546797,
 '774': 0.4157635467980295,
 '919': 0.40394088669950734,
 '1699': 0.4014778325123152,
 '1877': 0.4014778325123152,
 '878': 0.4009852216748768,
 '1445': 0.3990147783251231,
 '990': 0.3985221674876847,
 '1128': 0.3985221674876847,
 '1429': 0.39802955665024625,
 '1029': 0.39507389162561574,
 '1052': 0.3940886699507389,
 '1091': 0.393103448275862,
 '1126': 0.3926108374384236,
 '400': 0.39211822660098516,
 '1764': 0.39211822660098516,
 '1119': 0.3901477832512315,
 '955': 0.38620689655172413,
 '1971': 0.3847290640394088,
 '1269': 0.37832512315270933,
 '1276': 0.37832512315270933,
 '1931': 0.3753694581280788,
 '160': 0.37487684729064036,
 '311': 0.3694581280788177,
 '1423': 0.3694581280788177,
 '1425': 0.3694581280788177,
 '1450': 0.36847290640394087,
 '1461': 0.3679802955665024,
 '804': 0.3630541871921182,
 '1641': 0.3620689655172413,
 '1667': 0.3620689655172413,
 '402': 0.35812807881773395,
 '1781': 0.3561576354679803,
 '584': 0.35566502463054184,
 '1772': 0.35566502463054184,
 '1776': 0.35566502463054184,
 '1806': 0.35566502463054184,
 '1880': 0.3536945812807881,
 '1883': 0.3536945812807881,
 '102': 0.3527093596059113,
 '53': 0.3487684729064039,
 '159': 0.3487684729064039,
 '173': 0.3487684729064039,
 '1162': 0.3487684729064039,
 '1955': 0.3487684729064039,
 '1961': 0.3487684729064039,
 '66': 0.3423645320197044,
 '356': 0.3423645320197044,
 '358': 0.3423645320197044,
 '786': 0.341871921182266,
 '879': 0.3403940886699507,
 '6': 0.3394088669950739,
 '113': 0.3394088669950739,
 '423': 0.33891625615763543,
 '454': 0.3379310344827586,
 '472': 0.3379310344827586,
 '520': 0.3379310344827586,
 '521': 0.3379310344827586,
 '522': 0.3379310344827586,
 '596': 0.3379310344827586,
 '918': 0.3374384236453202,
 '631': 0.3364532019704433,
 '637': 0.33546798029556646,
 '651': 0.33497536945812806,
 '653': 0.33497536945812806,
 '662': 0.33497536945812806,
 '50': 0.3339901477832512,
 '729': 0.3339901477832512,
 '732': 0.3339901477832512,
 '740': 0.33300492610837434,
 '741': 0.33300492610837434,
 '751': 0.33300492610837434,
 '800': 0.33300492610837434,
 '119': 0.33251231527093594,
 '991': 0.33251231527093594,
 '144': 0.3320197044334975,
 '243': 0.3320197044334975,
 '244': 0.3320197044334975,
 '1870': 0.3315270935960591,
 '292': 0.32955665024630537,
 '294': 0.32955665024630537,
 '1068': 0.32857142857142857,
 '1127': 0.32857142857142857,
 '998': 0.3280788177339901,
 '1701': 0.3280788177339901,
 '814': 0.32709359605911326,
 '585': 0.32660098522167486,
 '796': 0.325615763546798,
 '287': 0.32413793103448274,
 '301': 0.3236453201970443,
 '513': 0.3236453201970443,
 '514': 0.3236453201970443,
 '416': 0.3226600985221675,
 '986': 0.3226600985221675,
 '987': 0.3226600985221675,
 '992': 0.3226600985221675,
 '362': 0.32068965517241377,
 '1026': 0.32019704433497537,
 '1049': 0.32019704433497537,
 '1077': 0.32019704433497537,
 '1082': 0.32019704433497537,
 '1084': 0.32019704433497537,
 '482': 0.3192118226600985,
 '483': 0.3192118226600985,
 '529': 0.3192118226600985,
 '1109': 0.31871921182266005,
 '1110': 0.31871921182266005,
 '1114': 0.31871921182266005,
 '1270': 0.31871921182266005,
 '425': 0.3172413793103448,
 '1444': 0.3172413793103448,
 '1504': 0.3172413793103448,
 '439': 0.3167487684729064,
 '757': 0.3147783251231527,
 '1935': 0.3137931034482758,
 '560': 0.3133004926108374,
 '567': 0.3133004926108374,
 '968': 0.3133004926108374,
 '674': 0.3113300492610837,
 '616': 0.31034482758620685,
 '1433': 0.31034482758620685,
 '888': 0.30935960591133005,
 '1674': 0.30935960591133005,
 '1826': 0.30935960591133005,
 '867': 0.3088669950738916,
 '908': 0.3088669950738916,
 '1933': 0.3088669950738916,
 '1549': 0.30788177339901474,
 '953': 0.30689655172413793,
 '1342': 0.3064039408866995,
 '832': 0.3059113300492611,
 '1306': 0.3059113300492611,
 '1419': 0.3049261083743842,
 '398': 0.30443349753694576,
 '100': 0.30344827586206896,
 '112': 0.30344827586206896,
 '868': 0.30344827586206896,
 '884': 0.30344827586206896,
 '885': 0.30344827586206896,
 '898': 0.30344827586206896,
 '900': 0.30344827586206896,
 '901': 0.30344827586206896,
 '1625': 0.30344827586206896,
 '1627': 0.30344827586206896,
 '1010': 0.3029556650246305,
 '1074': 0.3029556650246305,
 '1054': 0.3024630541871921,
 '1056': 0.3024630541871921,
 '1376': 0.3024630541871921,
 '1076': 0.30197044334975365,
 '1120': 0.30197044334975365,
 '925': 0.3004926108374384,
 '1782': 0.3004926108374384,
 '1337': 0.3,
 '1802': 0.3,
 '1228': 0.29950738916256153,
 '1230': 0.29950738916256153,
 '1335': 0.29950738916256153,
 '958': 0.29901477832512313,
 '1004': 0.2975369458128079,
 '1005': 0.2975369458128079,
 '1726': 0.2975369458128079,
 '1728': 0.2975369458128079,
 '1732': 0.2975369458128079,
 '1741': 0.2975369458128079,
 '1028': 0.2970443349753694,
 '1043': 0.2970443349753694,
 '1540': 0.2970443349753694,
 '1541': 0.2970443349753694,
 '788': 0.296551724137931,
 '791': 0.296551724137931,
 '48': 0.29556650246305416,
 '1190': 0.29556650246305416,
 '1282': 0.29556650246305416,
 '1446': 0.2945812807881773,
 '1447': 0.2945812807881773,
 '1462': 0.2945812807881773,
 '1463': 0.2945812807881773,
 '1467': 0.2945812807881773,
 '1480': 0.2945812807881773,
 '1487': 0.2945812807881773,
 '1497': 0.2945812807881773,
 '2009': 0.2945812807881773,
 '1958': 0.2940886699507389,
 '1370': 0.29261083743842364,
 '1489': 0.2916256157635468,
 '1490': 0.2916256157635468,
 '1493': 0.2916256157635468,
 '1494': 0.2916256157635468,
 '1498': 0.29113300492610833,
 '1968': 0.29014778325123153,
 '299': 0.28965517241379307,
 '1292': 0.28965517241379307,
 '1324': 0.28965517241379307,
 '1611': 0.28965517241379307,
 '1848': 0.28916256157635467,
 '1173': 0.2886699507389162,
 '1175': 0.2886699507389162,
 '1793': 0.2886699507389162,
 '1365': 0.28719211822660096,
 '1395': 0.28719211822660096,
 '1396': 0.28719211822660096,
 '1938': 0.28669950738916256,
 '1381': 0.2862068965517241,
 '1500': 0.2857142857142857,
 '1579': 0.28522167487684724,
 '1581': 0.28522167487684724,
 '1587': 0.28522167487684724,
 '1622': 0.28522167487684724,
 '1682': 0.28522167487684724,
 '1684': 0.28522167487684724,
 '1715': 0.28522167487684724,
 '1716': 0.28522167487684724,
 '1748': 0.28522167487684724,
 '931': 0.28472906403940884,
 '932': 0.28472906403940884,
 '1596': 0.28472906403940884,
 '1598': 0.28472906403940884,
 '1672': 0.28472906403940884,
 '1698': 0.28472906403940884,
 '1950': 0.28472906403940884,
 '379': 0.28423645320197044,
 '1451': 0.28423645320197044,
 '1452': 0.28423645320197044,
 '705': 0.283743842364532,
 '1760': 0.283743842364532,
 '38': 0.2832512315270936,
 '1785': 0.2832512315270936,
 '1808': 0.2832512315270936,
 '1837': 0.2832512315270936,
 '1812': 0.2827586206896551,
 '822': 0.2822660098522167,
 '1891': 0.2822660098522167,
 '1892': 0.2822660098522167,
 '88': 0.2817733990147783,
 '876': 0.2817733990147783,
 '882': 0.2817733990147783,
 '1994': 0.2798029556650246,
 '187': 0.2793103448275862,
 '253': 0.2793103448275862,
 '2014': 0.2793103448275862,
 '314': 0.27881773399014775,
 '704': 0.27881773399014775,
 '49': 0.2778325123152709,
 '1777': 0.2778325123152709,
 '1088': 0.2773399014778325,
 '1174': 0.27586206896551724,
 '302': 0.2753694581280788,
 '1216': 0.2743842364532019,
 '1570': 0.2743842364532019,
 '1835': 0.2743842364532019,
 '1836': 0.2743842364532019,
 '1872': 0.2738916256157635,
 '370': 0.2733990147783251,
 '1538': 0.2733990147783251,
 '952': 0.27241379310344827,
 '1899': 0.27241379310344827,
 '1919': 0.27241379310344827,
 '1921': 0.27241379310344827,
 '1438': 0.2714285714285714,
 '1075': 0.27044334975369455,
 '1967': 0.26995073891625615,
 '805': 0.2694581280788177,
 '1430': 0.2694581280788177,
 '2002': 0.2694581280788177,
 '1615': 0.26798029556650244,
 '1805': 0.26798029556650244,
 '1159': 0.2660098522167487,
 '1878': 0.2660098522167487,
 '1608': 0.2655172413793103,
 '1734': 0.2655172413793103,
 '1744': 0.2655172413793103,
 '1111': 0.26453201970443346,
 '1745': 0.26403940886699506,
 '1176': 0.2630541871921182,
 '1177': 0.2630541871921182,
 '1178': 0.2630541871921182,
 '1578': 0.26206896551724135,
 '1757': 0.2600985221674877,
 '1969': 0.258128078817734,
 '1809': 0.2571428571428571,
 '1827': 0.2566502463054187,
 '703': 0.25566502463054186,
 '1758': 0.2551724137931034,
 '787': 0.254679802955665,
 '790': 0.254679802955665,
 '1400': 0.254679802955665,
 '83': 0.25369458128078815,
 '821': 0.25369458128078815,
 '3': 0.25320197044334974,
 '36': 0.25320197044334974,
 '62': 0.25320197044334974,
 '801': 0.2527093596059113,
 '64': 0.2522167487684729,
 '250': 0.2522167487684729,
 '1700': 0.2517241379310345,
 '108': 0.25073891625615763,
 '109': 0.25073891625615763,
 '840': 0.25073891625615763,
 '168': 0.2502463054187192,
 '170': 0.2502463054187192,
 '278': 0.2502463054187192,
 '450': 0.24975369458128077,
 '486': 0.24975369458128077,
 '1304': 0.24975369458128077,
 '129': 0.24876847290640391,
 '141': 0.24827586206896549,
 '148': 0.24827586206896549,
 '149': 0.24827586206896549,
 '216': 0.24827586206896549,
 '218': 0.24827586206896549,
 '220': 0.24827586206896549,
 '225': 0.24827586206896549,
 '257': 0.24827586206896549,
 '261': 0.24827586206896549,
 '262': 0.24827586206896549,
 '266': 0.24827586206896549,
 '270': 0.24827586206896549,
 '271': 0.24827586206896549,
 '289': 0.24827586206896549,
 '337': 0.24778325123152709,
 '344': 0.24778325123152709,
 '371': 0.24778325123152709,
 '373': 0.24778325123152709,
 '417': 0.24778325123152709,
 '447': 0.24778325123152709,
 '526': 0.24778325123152709,
 '527': 0.24778325123152709,
 '543': 0.24778325123152709,
 '544': 0.24778325123152709,
 '545': 0.24778325123152709,
 '558': 0.24778325123152709,
 '578': 0.24778325123152709,
 '590': 0.24778325123152709,
 '626': 0.24778325123152709,
 '1986': 0.24778325123152709,
 '588': 0.24729064039408866,
 '789': 0.24729064039408866,
 '792': 0.24729064039408866,
 '811': 0.24729064039408866,
 '1953': 0.24729064039408866,
 '649': 0.24679802955665023,
 '650': 0.24679802955665023,
 '665': 0.24679802955665023,
 '726': 0.24581280788177337,
 '778': 0.24581280788177337,
 '795': 0.24532019704433497,
 '733': 0.24334975369458126,
 '864': 0.24285714285714283,
 '1156': 0.24285714285714283,
 '1081': 0.24236453201970443,
 '111': 0.241871921182266,
 '933': 0.241871921182266,
 '978': 0.241871921182266,
 '979': 0.241871921182266,
 '1934': 0.241871921182266,
 '1936': 0.241871921182266,
 '1428': 0.24137931034482757,
 '1108': 0.24088669950738914,
 '1468': 0.24088669950738914,
 '1225': 0.2403940886699507,
 '1659': 0.2403940886699507,
 '1665': 0.2403940886699507,
 '809': 0.23990147783251228,
 '946': 0.23990147783251228,
 '1165': 0.23990147783251228,
 '794': 0.23940886699507388,
 '1784': 0.23940886699507388,
 '60': 0.23891625615763545,
 '61': 0.23891625615763545,
 '1030': 0.23891625615763545,
 '1044': 0.23891625615763545,
 '1051': 0.23891625615763545,
 '1062': 0.23891625615763545,
 '1064': 0.23891625615763545,
 '1104': 0.23891625615763545,
 '1125': 0.23891625615763545,
 '1133': 0.23891625615763545,
 '1307': 0.23891625615763545,
 '110': 0.23842364532019703,
 '1195': 0.23842364532019703,
 '1212': 0.23842364532019703,
 '1235': 0.23842364532019703,
 '1255': 0.23842364532019703,
 '1291': 0.23842364532019703,
 '1294': 0.23842364532019703,
 '1327': 0.23842364532019703,
 '1328': 0.23842364532019703,
 '1339': 0.23842364532019703,
 '208': 0.2379310344827586,
 '1421': 0.2379310344827586,
 '1474': 0.2379310344827586,
 '1735': 0.23694581280788177,
 '1743': 0.23694581280788177,
 '1369': 0.23645320197044334,
 '1515': 0.23546798029556648,
 '1566': 0.23546798029556648,
 '1567': 0.23546798029556648,
 '1576': 0.23497536945812805,
 '1693': 0.23497536945812805,
 '1696': 0.23497536945812805,
 '1539': 0.23448275862068962,
 '1650': 0.23448275862068962,
 '1651': 0.23448275862068962,
 '1654': 0.23448275862068962,
 '1655': 0.23448275862068962,
 '1505': 0.23399014778325122,
 '1047': 0.2334975369458128,
 '1424': 0.23300492610837437,
 '158': 0.23251231527093594,
 '1460': 0.2320197044334975,
 '1729': 0.2320197044334975,
 '1295': 0.2315270935960591,
 '1708': 0.2315270935960591,
 '1727': 0.2315270935960591,
 '1733': 0.2315270935960591,
 '1736': 0.2315270935960591,
 '1740': 0.2315270935960591,
 '1742': 0.2315270935960591,
 '251': 0.23103448275862068,
 '252': 0.23054187192118225,
 '357': 0.23004926108374382,
 '1941': 0.2295566502463054,
 '1779': 0.22906403940886697,
 '1895': 0.22857142857142856,
 '654': 0.22807881773399014,
 '1859': 0.22807881773399014,
 '1866': 0.22807881773399014,
 '1868': 0.22807881773399014,
 '296': 0.2275862068965517,
 '313': 0.2275862068965517,
 '734': 0.2275862068965517,
 '1161': 0.2275862068965517,
 '784': 0.22709359605911328,
 '1157': 0.22709359605911328,
 '752': 0.22660098522167485,
 '1661': 0.22610837438423645,
 '1970': 0.22610837438423645,
 '1982': 0.22610837438423645,
 '597': 0.22561576354679802,
 '793': 0.2251231527093596,
 '655': 0.22463054187192116,
 '1310': 0.22463054187192116,
 '1778': 0.22463054187192116,
 '1983': 0.22463054187192116,
 '428': 0.22413793103448273,
 '1366': 0.22413793103448273,
 '2025': 0.22413793103448273,
 '234': 0.2231527093596059,
 '240': 0.22266009852216748,
 '241': 0.22266009852216748,
 '274': 0.22266009852216748,
 '1879': 0.22266009852216748,
 '1930': 0.22167487684729062,
 '1972': 0.22167487684729062,
 '1023': 0.2211822660098522,
 '1766': 0.2211822660098522,
 '145': 0.2206896551724138,
 '993': 0.21970443349753693,
 '1346': 0.21871921182266008,
 '1642': 0.21822660098522165,
 '874': 0.21773399014778325,
 '127': 0.2167487684729064,
 '1116': 0.2167487684729064,
 '1673': 0.21576354679802953,
 '1912': 0.21576354679802953,
 '0': 0.2152709359605911,
 '496': 0.2147783251231527,
 '497': 0.2147783251231527,
 '1048': 0.2147783251231527,
 '1086': 0.2147783251231527,
 '1260': 0.2147783251231527,
 '1804': 0.2147783251231527,
 '369': 0.21428571428571427,
 '549': 0.21428571428571427,
 '609': 0.21428571428571427,
 '802': 0.21428571428571427,
 '803': 0.21428571428571427,
 '1002': 0.21428571428571427,
 '295': 0.21330049261083742,
 '548': 0.21330049261083742,
 '1053': 0.21330049261083742,
 '1750': 0.212807881773399,
 '207': 0.2123152709359606,
 '1790': 0.2123152709359606,
 '172': 0.21133004926108373,
 '320': 0.21133004926108373,
 '613': 0.21133004926108373,
 '1752': 0.21133004926108373,
 '1754': 0.21133004926108373,
 '1261': 0.2108374384236453,
 '645': 0.20985221674876844,
 '646': 0.20985221674876844,
 '118': 0.20935960591133004,
 '288': 0.20935960591133004,
 '799': 0.20935960591133004,
 '1357': 0.20935960591133004,
 '354': 0.20788177339901476,
 '1194': 0.20788177339901476,
 '1209': 0.20788177339901476,
 '1214': 0.20788177339901476,
 '1298': 0.20738916256157633,
 '471': 0.20689655172413793,
 '606': 0.20689655172413793,
 '1422': 0.20689655172413793,
 '1755': 0.20689655172413793,
 '491': 0.2064039408866995,
 '1668': 0.20591133004926107,
 '1473': 0.20541871921182264,
 '1666': 0.20541871921182264,
 '1632': 0.2049261083743842,
 '1644': 0.2049261083743842,
 '1645': 0.2049261083743842,
 '1262': 0.20394088669950738,
 '1763': 0.20394088669950738,
 '1918': 0.20394088669950738,
 '865': 0.20344827586206896,
 '1309': 0.20344827586206896,
 '281': 0.20295566502463053,
 '1801': 0.20295566502463053,
 '1874': 0.20197044334975367,
 '798': 0.20147783251231527,
 '1747': 0.20147783251231527,
 '1481': 0.20098522167487684,
 '1885': 0.20098522167487684,
 '1547': 0.2004926108374384,
 '1548': 0.2004926108374384,
 '624': 0.19999999999999998,
 '224': 0.19950738916256155,
 '342': 0.19852216748768473,
 '492': 0.1980295566502463,
 '1502': 0.1980295566502463,
 '965': 0.19753694581280787,
 '707': 0.19704433497536944,
 '1465': 0.19704433497536944,
 '361': 0.196551724137931,
 '580': 0.19605911330049258,
 '1189': 0.19605911330049258,
 '1358': 0.19605911330049258,
 '731': 0.19556650246305418,
 '70': 0.19458128078817732,
 '71': 0.19458128078817732,
 '960': 0.19458128078817732,
 '453': 0.19359605911330047,
 '1803': 0.19359605911330047,
 '641': 0.19261083743842364,
 '758': 0.1921182266009852,
 '1882': 0.1921182266009852,
 '511': 0.19162561576354678,
 '638': 0.19162561576354678,
 '980': 0.19162561576354678,
 '360': 0.19113300492610835,
 '611': 0.19064039408866992,
 '1275': 0.19064039408866992,
 '1959': 0.19064039408866992,
 '298': 0.1896551724137931,
 '1070': 0.1896551724137931,
 '1583': 0.1896551724137931,
 '1762': 0.1896551724137931,
 '519': 0.18916256157635467,
 '940': 0.18916256157635467,
 '1580': 0.18916256157635467,
 '1714': 0.18916256157635467,
 '1124': 0.18866995073891624,
 '1140': 0.18866995073891624,
 '1172': 0.18866995073891624,
 '562': 0.1881773399014778,
 '1397': 0.1876847290640394,
 '1398': 0.1876847290640394,
 '1409': 0.1876847290640394,
 '1411': 0.1876847290640394,
 '1112': 0.18719211822660098,
 '656': 0.18669950738916255,
 '1229': 0.18669950738916255,
 '1382': 0.18669950738916255,
 '730': 0.18620689655172412,
 '926': 0.18620689655172412,
 '245': 0.1857142857142857,
 '1272': 0.1857142857142857,
 '1336': 0.1857142857142857,
 '427': 0.18522167487684726,
 '1286': 0.18472906403940886,
 '1363': 0.18472906403940886,
 '239': 0.18423645320197043,
 '1350': 0.18423645320197043,
 '999': 0.183743842364532,
 '1341': 0.183743842364532,
 '1351': 0.183743842364532,
 '1352': 0.183743842364532,
 '1388': 0.183743842364532,
 '1894': 0.183743842364532,
 '1427': 0.18325123152709358,
 '1884': 0.18275862068965515,
 '512': 0.18226600985221675,
 '883': 0.18226600985221675,
 '1966': 0.18226600985221675,
 '700': 0.18177339901477832,
 '994': 0.1812807881773399,
 '1293': 0.18078817733990146,
 '1278': 0.1798029556650246,
 '1787': 0.1798029556650246,
 '1960': 0.1798029556650246,
 '101': 0.1793103448275862,
 '833': 0.1793103448275862,
 '1024': 0.1793103448275862,
 '1080': 0.1793103448275862,
 '1113': 0.17881773399014778,
 '839': 0.17783251231527092,
 '1092': 0.1773399014778325,
 '1200': 0.17684729064039406,
 '1151': 0.17635467980295566,
 '1154': 0.17635467980295566,
 '2029': 0.17635467980295566,
 '1118': 0.17586206896551723,
 '217': 0.1753694581280788,
 '1129': 0.1753694581280788,
 '372': 0.17487684729064037,
 '1932': 0.17487684729064037,
 '1299': 0.17438423645320195,
 '773': 0.17389162561576355,
 '1021': 0.17389162561576355,
 '1022': 0.17389162561576355,
 '1687': 0.17389162561576355,
 '1710': 0.17389162561576355,

In [32]:
dict(sorted(nx.degree(G), key=lambda item: item[1], reverse=True))

{'22': 1505,
 '163': 1456,
 '401': 1410,
 '586': 1401,
 '813': 1373,
 '956': 1329,
 '937': 1326,
 '954': 1321,
 '84': 1263,
 '493': 1173,
 '1507': 1171,
 '1922': 1162,
 '1923': 1162,
 '1343': 1079,
 '1344': 1079,
 '5': 1062,
 '4': 1037,
 '155': 1024,
 '783': 1024,
 '1618': 1016,
 '587': 1015,
 '967': 979,
 '1259': 979,
 '1011': 974,
 '1163': 973,
 '1164': 973,
 '1158': 970,
 '1876': 970,
 '162': 962,
 '1101': 954,
 '1506': 950,
 '1503': 949,
 '1753': 947,
 '1751': 946,
 '1617': 945,
 '1680': 945,
 '1338': 938,
 '52': 935,
 '59': 932,
 '1543': 932,
 '1544': 932,
 '1756': 932,
 '1584': 931,
 '399': 930,
 '1652': 927,
 '1653': 927,
 '1662': 927,
 '1663': 927,
 '1749': 923,
 '1937': 920,
 '230': 913,
 '297': 907,
 '315': 905,
 '316': 905,
 '319': 904,
 '957': 902,
 '1345': 900,
 '205': 899,
 '82': 897,
 '65': 895,
 '1927': 885,
 '612': 870,
 '441': 867,
 '785': 865,
 '85': 845,
 '806': 845,
 '774': 844,
 '919': 820,
 '1699': 815,
 '1877': 815,
 '878': 814,
 '1445': 810,
 '990': 809,
 '1128': 809,
 '1429': 808,
 '1029': 802,
 '1052': 800,
 '1091': 798,
 '1126': 797,
 '400': 796,
 '1764': 796,
 '1119': 792,
 '955': 784,
 '1971': 781,
 '1269': 768,
 '1276': 768,
 '1931': 762,
 '160': 761,
 '311': 750,
 '1423': 750,
 '1425': 750,
 '1450': 748,
 '1461': 747,
 '804': 737,
 '1641': 735,
 '1667': 735,
 '402': 727,
 '1781': 723,
 '584': 722,
 '1772': 722,
 '1776': 722,
 '1806': 722,
 '1880': 718,
 '1883': 718,
 '102': 716,
 '53': 708,
 '159': 708,
 '173': 708,
 '1162': 708,
 '1955': 708,
 '1961': 708,
 '66': 695,
 '356': 695,
 '358': 695,
 '786': 694,
 '879': 691,
 '6': 689,
 '113': 689,
 '423': 688,
 '454': 686,
 '472': 686,
 '520': 686,
 '521': 686,
 '522': 686,
 '596': 686,
 '918': 685,
 '631': 683,
 '637': 681,
 '651': 680,
 '653': 680,
 '662': 680,
 '50': 678,
 '729': 678,
 '732': 678,
 '740': 676,
 '741': 676,
 '751': 676,
 '800': 676,
 '119': 675,
 '991': 675,
 '144': 674,
 '243': 674,
 '244': 674,
 '1870': 673,
 '292': 669,
 '294': 669,
 '1068': 667,
 '1127': 667,
 '998': 666,
 '1701': 666,
 '814': 664,
 '585': 663,
 '796': 661,
 '287': 658,
 '301': 657,
 '513': 657,
 '514': 657,
 '416': 655,
 '986': 655,
 '987': 655,
 '992': 655,
 '362': 651,
 '1026': 650,
 '1049': 650,
 '1077': 650,
 '1082': 650,
 '1084': 650,
 '482': 648,
 '483': 648,
 '529': 648,
 '1109': 647,
 '1110': 647,
 '1114': 647,
 '1270': 647,
 '425': 644,
 '1444': 644,
 '1504': 644,
 '439': 643,
 '757': 639,
 '1935': 637,
 '560': 636,
 '567': 636,
 '968': 636,
 '674': 632,
 '616': 630,
 '1433': 630,
 '888': 628,
 '1674': 628,
 '1826': 628,
 '867': 627,
 '908': 627,
 '1933': 627,
 '1549': 625,
 '953': 623,
 '1342': 622,
 '832': 621,
 '1306': 621,
 '1419': 619,
 '398': 618,
 '100': 616,
 '112': 616,
 '868': 616,
 '884': 616,
 '885': 616,
 '898': 616,
 '900': 616,
 '901': 616,
 '1625': 616,
 '1627': 616,
 '1010': 615,
 '1074': 615,
 '1054': 614,
 '1056': 614,
 '1376': 614,
 '1076': 613,
 '1120': 613,
 '925': 610,
 '1782': 610,
 '1337': 609,
 '1802': 609,
 '1228': 608,
 '1230': 608,
 '1335': 608,
 '958': 607,
 '1004': 604,
 '1005': 604,
 '1726': 604,
 '1728': 604,
 '1732': 604,
 '1741': 604,
 '1028': 603,
 '1043': 603,
 '1540': 603,
 '1541': 603,
 '788': 602,
 '791': 602,
 '48': 600,
 '1190': 600,
 '1282': 600,
 '1446': 598,
 '1447': 598,
 '1462': 598,
 '1463': 598,
 '1467': 598,
 '1480': 598,
 '1487': 598,
 '1497': 598,
 '2009': 598,
 '1958': 597,
 '1370': 594,
 '1489': 592,
 '1490': 592,
 '1493': 592,
 '1494': 592,
 '1498': 591,
 '1968': 589,
 '299': 588,
 '1292': 588,
 '1324': 588,
 '1611': 588,
 '1848': 587,
 '1173': 586,
 '1175': 586,
 '1793': 586,
 '1365': 583,
 '1395': 583,
 '1396': 583,
 '1938': 582,
 '1381': 581,
 '1500': 580,
 '1579': 579,
 '1581': 579,
 '1587': 579,
 '1622': 579,
 '1682': 579,
 '1684': 579,
 '1715': 579,
 '1716': 579,
 '1748': 579,
 '931': 578,
 '932': 578,
 '1596': 578,
 '1598': 578,
 '1672': 578,
 '1698': 578,
 '1950': 578,
 '379': 577,
 '1451': 577,
 '1452': 577,
 '705': 576,
 '1760': 576,
 '38': 575,
 '1785': 575,
 '1808': 575,
 '1837': 575,
 '1812': 574,
 '822': 573,
 '1891': 573,
 '1892': 573,
 '88': 572,
 '876': 572,
 '882': 572,
 '1994': 568,
 '187': 567,
 '253': 567,
 '2014': 567,
 '314': 566,
 '704': 566,
 '49': 564,
 '1777': 564,
 '1088': 563,
 '1174': 560,
 '302': 559,
 '1216': 557,
 '1570': 557,
 '1835': 557,
 '1836': 557,
 '1872': 556,
 '370': 555,
 '1538': 555,
 '952': 553,
 '1899': 553,
 '1919': 553,
 '1921': 553,
 '1438': 551,
 '1075': 549,
 '1967': 548,
 '805': 547,
 '1430': 547,
 '2002': 547,
 '1615': 544,
 '1805': 544,
 '1159': 540,
 '1878': 540,
 '1608': 539,
 '1734': 539,
 '1744': 539,
 '1111': 537,
 '1745': 536,
 '1176': 534,
 '1177': 534,
 '1178': 534,
 '1578': 532,
 '1757': 528,
 '1969': 524,
 '1809': 522,
 '1827': 521,
 '703': 519,
 '1758': 518,
 '787': 517,
 '790': 517,
 '1400': 517,
 '83': 515,
 '821': 515,
 '3': 514,
 '36': 514,
 '62': 514,
 '801': 513,
 '64': 512,
 '250': 512,
 '1700': 511,
 '108': 509,
 '109': 509,
 '840': 509,
 '168': 508,
 '170': 508,
 '278': 508,
 '450': 507,
 '486': 507,
 '1304': 507,
 '129': 505,
 '141': 504,
 '148': 504,
 '149': 504,
 '216': 504,
 '218': 504,
 '220': 504,
 '225': 504,
 '257': 504,
 '261': 504,
 '262': 504,
 '266': 504,
 '270': 504,
 '271': 504,
 '289': 504,
 '337': 503,
 '344': 503,
 '371': 503,
 '373': 503,
 '417': 503,
 '447': 503,
 '526': 503,
 '527': 503,
 '543': 503,
 '544': 503,
 '545': 503,
 '558': 503,
 '578': 503,
 '590': 503,
 '626': 503,
 '1986': 503,
 '588': 502,
 '789': 502,
 '792': 502,
 '811': 502,
 '1953': 502,
 '649': 501,
 '650': 501,
 '665': 501,
 '726': 499,
 '778': 499,
 '795': 498,
 '733': 494,
 '864': 493,
 '1156': 493,
 '1081': 492,
 '111': 491,
 '933': 491,
 '978': 491,
 '979': 491,
 '1934': 491,
 '1936': 491,
 '1428': 490,
 '1108': 489,
 '1468': 489,
 '1225': 488,
 '1659': 488,
 '1665': 488,
 '809': 487,
 '946': 487,
 '1165': 487,
 '794': 486,
 '1784': 486,
 '60': 485,
 '61': 485,
 '1030': 485,
 '1044': 485,
 '1051': 485,
 '1062': 485,
 '1064': 485,
 '1104': 485,
 '1125': 485,
 '1133': 485,
 '1307': 485,
 '110': 484,
 '1195': 484,
 '1212': 484,
 '1235': 484,
 '1255': 484,
 '1291': 484,
 '1294': 484,
 '1327': 484,
 '1328': 484,
 '1339': 484,
 '208': 483,
 '1421': 483,
 '1474': 483,
 '1735': 481,
 '1743': 481,
 '1369': 480,
 '1515': 478,
 '1566': 478,
 '1567': 478,
 '1576': 477,
 '1693': 477,
 '1696': 477,
 '1539': 476,
 '1650': 476,
 '1651': 476,
 '1654': 476,
 '1655': 476,
 '1505': 475,
 '1047': 474,
 '1424': 473,
 '158': 472,
 '1460': 471,
 '1729': 471,
 '1295': 470,
 '1708': 470,
 '1727': 470,
 '1733': 470,
 '1736': 470,
 '1740': 470,
 '1742': 470,
 '251': 469,
 '252': 468,
 '357': 467,
 '1941': 466,
 '1779': 465,
 '1895': 464,
 '654': 463,
 '1859': 463,
 '1866': 463,
 '1868': 463,
 '296': 462,
 '313': 462,
 '734': 462,
 '1161': 462,
 '784': 461,
 '1157': 461,
 '752': 460,
 '1661': 459,
 '1970': 459,
 '1982': 459,
 '597': 458,
 '793': 457,
 '655': 456,
 '1310': 456,
 '1778': 456,
 '1983': 456,
 '428': 455,
 '1366': 455,
 '2025': 455,
 '234': 453,
 '240': 452,
 '241': 452,
 '274': 452,
 '1879': 452,
 '1930': 450,
 '1972': 450,
 '1023': 449,
 '1766': 449,
 '145': 448,
 '993': 446,
 '1346': 444,
 '1642': 443,
 '874': 442,
 '127': 440,
 '1116': 440,
 '1673': 438,
 '1912': 438,
 '0': 437,
 '496': 436,
 '497': 436,
 '1048': 436,
 '1086': 436,
 '1260': 436,
 '1804': 436,
 '369': 435,
 '549': 435,
 '609': 435,
 '802': 435,
 '803': 435,
 '1002': 435,
 '295': 433,
 '548': 433,
 '1053': 433,
 '1750': 432,
 '207': 431,
 '1790': 431,
 '172': 429,
 '320': 429,
 '613': 429,
 '1752': 429,
 '1754': 429,
 '1261': 428,
 '645': 426,
 '646': 426,
 '118': 425,
 '288': 425,
 '799': 425,
 '1357': 425,
 '354': 422,
 '1194': 422,
 '1209': 422,
 '1214': 422,
 '1298': 421,
 '471': 420,
 '606': 420,
 '1422': 420,
 '1755': 420,
 '491': 419,
 '1668': 418,
 '1473': 417,
 '1666': 417,
 '1632': 416,
 '1644': 416,
 '1645': 416,
 '1262': 414,
 '1763': 414,
 '1918': 414,
 '865': 413,
 '1309': 413,
 '281': 412,
 '1801': 412,
 '1874': 410,
 '798': 409,
 '1747': 409,
 '1481': 408,
 '1885': 408,
 '1547': 407,
 '1548': 407,
 '624': 406,
 '224': 405,
 '342': 403,
 '492': 402,
 '1502': 402,
 '965': 401,
 '707': 400,
 '1465': 400,
 '361': 399,
 '580': 398,
 '1189': 398,
 '1358': 398,
 '731': 397,
 '70': 395,
 '71': 395,
 '960': 395,
 '453': 393,
 '1803': 393,
 '641': 391,
 '758': 390,
 '1882': 390,
 '511': 389,
 '638': 389,
 '980': 389,
 '360': 388,
 '611': 387,
 '1275': 387,
 '1959': 387,
 '298': 385,
 '1070': 385,
 '1583': 385,
 '1762': 385,
 '519': 384,
 '940': 384,
 '1580': 384,
 '1714': 384,
 '1124': 383,
 '1140': 383,
 '1172': 383,
 '562': 382,
 '1397': 381,
 '1398': 381,
 '1409': 381,
 '1411': 381,
 '1112': 380,
 '656': 379,
 '1229': 379,
 '1382': 379,
 '730': 378,
 '926': 378,
 '245': 377,
 '1272': 377,
 '1336': 377,
 '427': 376,
 '1286': 375,
 '1363': 375,
 '239': 374,
 '1350': 374,
 '999': 373,
 '1341': 373,
 '1351': 373,
 '1352': 373,
 '1388': 373,
 '1894': 373,
 '1427': 372,
 '1884': 371,
 '512': 370,
 '883': 370,
 '1966': 370,
 '700': 369,
 '994': 368,
 '1293': 367,
 '1278': 365,
 '1787': 365,
 '1960': 365,
 '101': 364,
 '833': 364,
 '1024': 364,
 '1080': 364,
 '1113': 363,
 '839': 361,
 '1092': 360,
 '1200': 359,
 '1151': 358,
 '1154': 358,
 '2029': 358,
 '1118': 357,
 '217': 356,
 '1129': 356,
 '372': 355,
 '1932': 355,
 '1299': 354,
 '773': 353,
 '1021': 353,
 '1022': 353,
 '1687': 353,
 '1710': 353,
 '1987': 353,
 '1640': 352,
 '1325': 351,
 '1469': 351,
 '1470': 351,
 '913': 350,
 '1495': 349,
 '157': 348,
 '473': 348,
 '595': 348,
 '1437': 347,
 '1095': 346,
 '1130': 346,
 '1916': 345,
 '1': 344,
 '359': 344,
 '1559': 344,
 '2021': 344,
 '1105': 343,
 '1392': 343,
 '81': 342,
 '1603': 342,
 '1604': 342,
 '1067': 341,
 '1600': 341,
 '1942': 341,
 '1943': 341,
 '161': 340,
 '557': 340,
 '1609': 340,
 '1881': 340,
 '1940': 340,
 '130': 339,
 '1957': 338,
 '1633': 337,
 '1646': 337,
 '1647': 337,
 '1685': 337,
 '1466': 336,
 '1488': 336,
 '1737': 336,
 '341': 335,
 '349': 335,
 '424': 335,
 '556': 335,
 '617': 335,
 '875': 335,
 '682': 334,
 '300': 333,
 '661': 333,
 '1160': 333,
 '39': 332,
 '1186': 331,
 '1718': 331,
 '303': 330,
 '312': 330,
 '524': 330,
 '1906': 330,
 '34': 329,
 '1277': 329,
 '1771': 329,
 '1794': 329,
 '1796': 329,
 '1085': 328,
 '1492': 328,
 '1846': 328,
 '186': 327,
 '996': 327,
 '1103': 327,
 '1193': 327,
 '1213': 327,
 '1875': 327,
 '1903': 327,
 '1904': 327,
 '827': 326,
 '841': 326,
 '523': 325,
 '179': 324,
 '277': 324,
 '610': 324,
 '934': 324,
 '1786': 324,
 '660': 323,
 '961': 323,
 '263': 322,
 '897': 322,
 '1274': 322,
 '375': 321,
 '997': 321,
 '1090': 321,
 '1093': 321,
 '1196': 321,
 '1236': 321,
 '1239': 321,
 '1329': 321,
 '1008': 320,
 '1009': 320,
 '1115': 320,
 '1182': 320,
 '1628': 320,
 '2012': 319,
 '1036': 318,
 '1420': 318,
 '37': 317,
 '1626': 317,
 '1886': 317,
 '1649': 315,
 '1844': 315,
 '443': 314,
 '445': 314,
 '810': 314,
 '1671': 314,
 '56': 313,
 '355': 313,
 '484': 312,
 '531': 312,
 '534': 312,
 '536': 312,
 '538': 312,
 '539': 312,
 '962': 312,
 '945': 311,
 '1072': 311,
 '1853': 311,
 '69': 310,
 '455': 310,
 '40': 309,
 '675': 308,
 '686': 308,
 '688': 308,
 '692': 308,
 '1237': 308,
 '1362': 308,
 '630': 307,
 '911': 307,
 '747': 306,
 '749': 306,
 '1032': 306,
 '1898': 306,
 '449': 305,
 '1250': 305,
 '1254': 305,
 '1367': 305,
 '132': 304,
 '488': 304,
 '555': 304,
 '657': 304,
 '853': 304,
 '1635': 304,
 '1686': 304,
 '448': 303,
 '896': 303,
 '1783': 303,
 '1838': 303,
 '2027': 303,
 '828': 302,
 '1122': 302,
 '1683': 302,
 '1695': 302,
 '2020': 302,
 '861': 301,
 '887': 301,
 '1271': 301,
 '426': 300,
 '1624': 300,
 '1951': 300,
 '1988': 300,
 '1203': 299,
 '1206': 299,
 '1767': 299,
 '1948': 299,
 '1954': 299,
 '1992': 298,
 '1019': 296,
 '1079': 296,
 '171': 295,
 '642': 295,
 '1025': 295,
 '1087': 295,
 '939': 294,
 '1106': 294,
 '1811': 294,
 '594': 293,
 '1040': 293,
 '1042': 293,
 '1464': 293,
 '1491': 293,
 '857': 292,
 '858': 292,
 '859': 292,
 '636': 290,
 '736': 290,
 '1168': 290,
 '1170': 290,
 '1597': 290,
 '1738': 290,
 '509': 289,
 '1141': 289,
 '1739': 289,
 '175': 288,
 '242': 288,
 '659': 288,
 '750': 288,
 '824': 288,
 '1678': 288,
 '1681': 288,
 '156': 287,
 '280': 287,
 '142': 286,
 '623': 286,
 '1545': 286,
 '1602': 286,
 '1660': 286,
 '79': 285,
 '80': 285,
 '176': 285,
 '177': 285,
 '293': 285,
 '1078': 285,
 '1765': 285,
 '598': 283,
 '728': 283,
 '820': 283,
 '1065': 283,
 '1657': 283,
 '117': 281,
 '122': 281,
 '899': 281,
 '1378': 281,
 '1121': 280,
 '1788': 280,
 '291': 279,
 '397': 279,
 '639': 279,
 '985': 279,
 '1354': 279,
 '658': 278,
 '1027': 278,
 '481': 277,
 '1089': 277,
 '1171': 277,
 '1791': 277,
 '421': 276,
 '1107': 276,
 '1220': 276,
 '1308': 276,
 '1913': 276,
 '1917': 276,
 '1984': 276,
 '764': 275,
 '767': 275,
 '347': 274,
 '1221': 274,
 '572': 272,
 '574': 272,
 '1281': 272,
 '1849': 272,
 '1356': 271,
 '1364': 271,
 '1780': 271,
 '389': 269,
 '391': 269,
 '392': 269,
 '1167': 269,
 '1457': 269,
 '866': 268,
 '906': 268,
 '1440': 268,
 '1636': 268,
 '709': 266,
 '737': 266,
 '1476': 266,
 '1518': 266,
 '1648': 266,
 '995': 265,
 '1006': 265,
 '1590': 265,
 '1592': 265,
 '1599': 265,
 '779': 264,
 '330': 263,
 '942': 263,
 '1033': 263,
 '1391': 263,
 '1893': 263,
 '1166': 262,
 '1169': 262,
 '1455': 262,
 '909': 261,
 '930': 261,
 '1069': 260,
 '1449': 260,
 '1588': 260,
 '1730': 260,
 '941': 259,
 '1956': 259,
 '2026': 259,
 '189': 258,
 '1311': 257,
 '1415': 257,
 '1435': 256,
 '238': 254,
 '1017': 254,
 '106': 253,
 '1385': 253,
 '1386': 253,
 '633': 252,
 '1612': 252,
 '530': 251,
 '652': 251,
 '1679': 251,
 ...}

In [33]:
num_nodos = len(G)
grado_medio = sum(dict(G.degree()).values()) / num_nodos
grado_medio

308.77104874446087

### Centralidad de cercanía

In [34]:
dict(sorted(nx.closeness_centrality(G).items(), key=lambda item: item[1], reverse=True))

{'22': 0.744054561657634,
 '163': 0.7231733053453636,
 '401': 0.7046097048733286,
 '586': 0.7010886125113852,
 '813': 0.6903557086566456,
 '956': 0.6741380625376427,
 '937': 0.6730600165954184,
 '954': 0.6712709150095719,
 '84': 0.6511916406049535,
 '493': 0.6223068462952217,
 '1507': 0.6216940379778458,
 '1922': 0.618345049526447,
 '1923': 0.618345049526447,
 '1343': 0.5947529868737659,
 '1344': 0.5947529868737659,
 '5': 0.5900283136135537,
 '4': 0.5832150536411108,
 '783': 0.5797339720537212,
 '155': 0.5792021060243142,
 '1618': 0.577612347270359,
 '587': 0.5773482355432121,
 '1259': 0.5679984665465609,
 '1163': 0.5664695339313616,
 '1164': 0.5664695339313616,
 '967': 0.5659617172268062,
 '1158': 0.5657081501491957,
 '1876': 0.5657081501491957,
 '1011': 0.5646961498805925,
 '162': 0.5636877638986628,
 '1506': 0.5606840990821513,
 '1503': 0.5604352379640501,
 '1753': 0.5599381778860332,
 '1101': 0.559689978339098,
 '1751': 0.559689978339098,
 '1617': 0.5594419987297319,
 '1680': 0.5574660446503333,
 '52': 0.5569742351711534,
 '59': 0.5562381458735705,
 '1756': 0.5562381458735705,
 '399': 0.5557484996184,
 '1338': 0.5557484996184,
 '1543': 0.5542847195491681,
 '1544': 0.5542847195491681,
 '1584': 0.5540415055432228,
 '1749': 0.5540415055432228,
 '1937': 0.5533131424772151,
 '1652': 0.5530707801721441,
 '1653': 0.5530707801721441,
 '1662': 0.5530707801721441,
 '1663': 0.5530707801721441,
 '230': 0.5516210533564897,
 '297': 0.5501789068117668,
 '315': 0.5496998655346125,
 '316': 0.5496998655346125,
 '319': 0.5494606575861639,
 '957': 0.5489828657100021,
 '1345': 0.5485059040543028,
 '205': 0.5482677338831979,
 '82': 0.5477920135067267,
 '65': 0.5473171179596901,
 '1927': 0.5449549379080729,
 '612': 0.5414496531445132,
 '441': 0.5407540004852269,
 '785': 0.540291224275997,
 '85': 0.5357066572477747,
 '774': 0.535479470370231,
 '806': 0.5352524761055553,
 '919': 0.5300842112229239,
 '1699': 0.5289738546849623,
 '1877': 0.5289738546849623,
 '878': 0.5287523413454794,
 '1445': 0.5278681401057713,
 '990': 0.52764755166444,
 '1429': 0.5274271475075208,
 '1029': 0.526108579638752,
 '1128': 0.5258894590308225,
 '1052': 0.5256705208713592,
 '1091': 0.5252331909871069,
 '1126': 0.5250147988079022,
 '400': 0.5247965881683312,
 '1764': 0.5247965881683312,
 '1119': 0.523925556486724,
 '955': 0.5221921385992576,
 '1971': 0.5215450603605969,
 '1269': 0.5187594869075616,
 '1276': 0.5187594869075616,
 '160': 0.517271852164279,
 '1931': 0.5170600291289946,
 '311': 0.5149513014408666,
 '1423': 0.5149513014408666,
 '1425': 0.5149513014408666,
 '1450': 0.5145316182286083,
 '1461': 0.5143220330480672,
 '804': 0.5118202639371726,
 '1641': 0.5118202639371726,
 '1667': 0.5118202639371726,
 '402': 0.5101658954072746,
 '1781': 0.5093427152613977,
 '584': 0.5091373351342761,
 '1772': 0.5091373351342761,
 '1776': 0.5091373351342761,
 '1806': 0.5091373351342761,
 '1880': 0.5083174682500019,
 '1883': 0.5083174682500019,
 '102': 0.5079085241886584,
 '53': 0.5062793067894967,
 '159': 0.5062793067894967,
 '173': 0.5062793067894967,
 '1162': 0.5062793067894967,
 '1955': 0.5060763892316653,
 '1961': 0.5060763892316653,
 '66': 0.503654005238534,
 '356': 0.503654005238534,
 '358': 0.503654005238534,
 '786': 0.503453186257179,
 '879': 0.5028516890215073,
 '6': 0.5024514887119002,
 '113': 0.5024514887119002,
 '423': 0.5022516273400973,
 '454': 0.501852381213436,
 '472': 0.501852381213436,
 '520': 0.501852381213436,
 '521': 0.501852381213436,
 '522': 0.501852381213436,
 '596': 0.501852381213436,
 '918': 0.5016529960798589,
 '631': 0.5012547007276716,
 '637': 0.5008570373395498,
 '651': 0.5006584421621748,
 '653': 0.5006584421621748,
 '662': 0.5006584421621748,
 '50': 0.5002617239037261,
 '729': 0.5002617239037261,
 '732': 0.5002617239037261,
 '740': 0.4998656338610471,
 '741': 0.4998656338610471,
 '751': 0.4998656338610471,
 '800': 0.4998656338610471,
 '119': 0.4996678239544934,
 '991': 0.4996678239544934,
 '144': 0.499470170543119,
 '243': 0.499470170543119,
 '244': 0.499470170543119,
 '1870': 0.49927267344128307,
 '292': 0.49848424442676864,
 '294': 0.49848424442676864,
 '1068': 0.49809096297159955,
 '1127': 0.49809096297159955,
 '998': 0.49789455486317225,
 '1701': 0.49789455486317225,
 '814': 0.497502202968087,
 '585': 0.49730625881567736,
 '796': 0.49691483318890395,
 '301': 0.49613382755717284,
 '513': 0.49613382755717284,
 '514': 0.49613382755717284,
 '416': 0.49574424465371214,
 '986': 0.49574424465371214,
 '987': 0.49574424465371214,
 '992': 0.49574424465371214,
 '287': 0.4955496825482751,
 '362': 0.49496691145942956,
 '1026': 0.4947729589079173,
 '1049': 0.4947729589079173,
 '1077': 0.4947729589079173,
 '1082': 0.4947729589079173,
 '1084': 0.4947729589079173,
 '482': 0.49438550944910137,
 '483': 0.49438550944910137,
 '529': 0.49438550944910137,
 '1109': 0.49419201218512915,
 '1110': 0.49419201218512915,
 '1114': 0.49419201218512915,
 '1270': 0.49419201218512915,
 '425': 0.49361242812079936,
 '1444': 0.49361242812079936,
 '1504': 0.49361242812079936,
 '439': 0.4934195354173524,
 '757': 0.49264946981389185,
 '1935': 0.4922653376736861,
 '560': 0.49207349615471735,
 '567': 0.49207349615471735,
 '674': 0.4913076230089513,
 '616': 0.49092557975622275,
 '1433': 0.49092557975622275,
 '888': 0.49054413019930265,
 '968': 0.49054413019930265,
 '1674': 0.49054413019930265,
 '1826': 0.49054413019930265,
 '867': 0.4903536276244679,
 '908': 0.4903536276244679,
 '1933': 0.4903536276244679,
 '1549': 0.48997306601979235,
 '1342': 0.48940332989651353,
 '832': 0.48921371217861487,
 '1306': 0.48921371217861487,
 '398': 0.4886457396025561,
 '100': 0.48826782333062835,
 '112': 0.48826782333062835,
 '868': 0.48826782333062835,
 '884': 0.48826782333062835,
 '885': 0.48826782333062835,
 '898': 0.48826782333062835,
 '900': 0.48826782333062835,
 '901': 0.48826782333062835,
 '1625': 0.48826782333062835,
 '1627': 0.48826782333062835,
 '953': 0.48807908431890407,
 '1010': 0.48807908431890407,
 '1054': 0.48789049116422134,
 '1056': 0.48789049116422134,
 '1376': 0.48789049116422134,
 '1076': 0.4877020436975685,
 '1120': 0.4877020436975685,
 '1419': 0.4873255851536105,
 '925': 0.4871375737395853,
 '1782': 0.4871375737395853,
 '1802': 0.4869497073401485,
 '1228': 0.4867619857875886,
 '1230': 0.4867619857875886,
 '1335': 0.4867619857875886,
 '958': 0.48657440891445275,
 '1004': 0.48601254470092564,
 '1005': 0.48601254470092564,
 '1074': 0.48601254470092564,
 '1726': 0.48601254470092564,
 '1728': 0.48601254470092564,
 '1732': 0.48601254470092564,
 '1741': 0.48601254470092564,
 '1028': 0.485825544876108,
 '1043': 0.485825544876108,
 '1540': 0.485825544876108,
 '1541': 0.485825544876108,
 '788': 0.48563868889730955,
 '791': 0.48563868889730955,
 '1337': 0.4854519765986178,
 '48': 0.48526540781437544,
 '1190': 0.48526540781437544,
 '1282': 0.48526540781437544,
 '1446': 0.48489270012788205,
 '1447': 0.48489270012788205,
 '1462': 0.48489270012788205,
 '1463': 0.48489270012788205,
 '1467': 0.48489270012788205,
 '1480': 0.48489270012788205,
 '1487': 0.48489270012788205,
 '1497': 0.48489270012788205,
 '2009': 0.48489270012788205,
 '1958': 0.4845205645176534,
 '1370': 0.4841489996675632,
 '1489': 0.4837780042655191,
 '1490': 0.4837780042655191,
 '1493': 0.4837780042655191,
 '1494': 0.4837780042655191,
 '1498': 0.4835927196985848,
 '299': 0.4830377165772781,
 '1292': 0.4830377165772781,
 '1324': 0.4830377165772781,
 '1611': 0.4830377165772781,
 '1848': 0.4828529985212256,
 '1173': 0.4826684216869284,
 '1175': 0.4826684216869284,
 '1793': 0.4826684216869284,
 '1365': 0.48211553689690906,
 '1395': 0.48211553689690906,
 '1396': 0.48211553689690906,
 '1381': 0.48174765018428267,
 '1938': 0.48174765018428267,
 '1500': 0.4815639172894755,
 '1579': 0.4813803244883739,
 '1581': 0.4813803244883739,
 '1587': 0.4813803244883739,
 '1622': 0.4813803244883739,
 '1682': 0.4813803244883739,
 '1684': 0.4813803244883739,
 '1715': 0.4813803244883739,
 '1716': 0.4813803244883739,
 '1748': 0.4813803244883739,
 '1596': 0.48119687162080976,
 '1598': 0.48119687162080976,
 '1672': 0.48119687162080976,
 '1698': 0.48119687162080976,
 '931': 0.481013558526859,
 '932': 0.481013558526859,
 '1451': 0.481013558526859,
 '1452': 0.481013558526859,
 '1950': 0.481013558526859,
 '1760': 0.4808303850468411,
 '38': 0.48064735102131895,
 '379': 0.48064735102131895,
 '1785': 0.48064735102131895,
 '1808': 0.48064735102131895,
 '1837': 0.48064735102131895,
 '705': 0.48046445629109774,
 '1812': 0.48046445629109774,
 '822': 0.4802817006972251,
 '1891': 0.4802817006972251,
 '1892': 0.4802817006972251,
 '88': 0.4800990840809904,
 '876': 0.4800990840809904,
 '882': 0.4800990840809904,
 '1968': 0.4800990840809904,
 '187': 0.47918808012637754,
 '253': 0.47918808012637754,
 '1994': 0.47918808012637754,
 '314': 0.4790062940565269,
 '704': 0.4790062940565269,
 '2014': 0.4790062940565269,
 '49': 0.47864313538021414,
 '1088': 0.4784617624604035,
 '1777': 0.47828052694432005,
 '1174': 0.4779184674992449,
 '302': 0.4777376432587987,
 '1570': 0.4773764049652192,
 '1835': 0.4773764049652192,
 '1836': 0.4773764049652192,
 '1872': 0.47719599060204265,
 '370': 0.4770157125549697,
 '1538': 0.4770157125549697,
 '1899': 0.4766555647916213,
 '1919': 0.4766555647916213,
 '1921': 0.4766555647916213,
 '1438': 0.47629596044247635,
 '1967': 0.4757575701330086,
 '1216': 0.4755783770745781,
 '1430': 0.4755783770745781,
 '2002': 0.4755783770745781,
 '805': 0.4752203956089593,
 '1615': 0.475041606897293,
 '1805': 0.475041606897293,
 '952': 0.4748629526637852,
 '1159': 0.47432779531668107,
 '1878': 0.47432779531668107,
 '1075': 0.4741496774814138,
 '1608': 0.4741496774814138,
 '1734': 0.4741496774814138,
 '1744': 0.4741496774814138,
 '1111': 0.4737938428266435,
 '1745': 0.4736161257063034,
 '1176': 0.47326109112931214,
 '1177': 0.47326109112931214,
 '1178': 0.47326109112931214,
 '1757': 0.47219917394652383,
 '1578': 0.47114201161679287,
 '1827': 0.4709662779309977,
 '703': 0.470615203553114,
 '1758': 0.4704398625681836,
 '787': 0.4702646521910632,
 '790': 0.4702646521910632,
 '1400': 0.4702646521910632,
 '83': 0.469914622676965,
 '821': 0.469914622676965,
 '3': 0.46973980324888576,
 '36': 0.46973980324888576,
 '62': 0.46973980324888576,
 '801': 0.46956511384641314,
 '64': 0.46939055432453713,
 '250': 0.46939055432453713,
 '1809': 0.46939055432453713,
 '1700': 0.46921612453846334,
 '108': 0.4688676535956201,
 '109': 0.4688676535956201,
 '840': 0.4688676535956201,
 '168': 0.4686936121503359,
 '170': 0.4686936121503359,
 '278': 0.4686936121503359,
 '450': 0.4685196998638237,
 '486': 0.4685196998638237,
 '1304': 0.4685196998638237,
 '129': 0.46817226219243785,
 '1969': 0.46817226219243785,
 '141': 0.4679987365207579,
 '148': 0.4679987365207579,
 '149': 0.4679987365207579,
 '216': 0.4679987365207579,
 '218': 0.4679987365207579,
 '220': 0.4679987365207579,
 '225': 0.4679987365207579,
 '257': 0.4679987365207579,
 '261': 0.4679987365207579,
 '262': 0.4679987365207579,
 '266': 0.4679987365207579,
 '270': 0.4679987365207579,
 '271': 0.4679987365207579,
 '289': 0.4679987365207579,
 '337': 0.4678253394342367,
 '344': 0.4678253394342367,
 '371': 0.4678253394342367,
 '373': 0.4678253394342367,
 '417': 0.4678253394342367,
 '447': 0.4678253394342367,
 '526': 0.4678253394342367,
 '527': 0.4678253394342367,
 '543': 0.4678253394342367,
 '544': 0.4678253394342367,
 '545': 0.4678253394342367,
 '558': 0.4678253394342367,
 '578': 0.4678253394342367,
 '590': 0.4678253394342367,
 '626': 0.4678253394342367,
 '1986': 0.4678253394342367,
 '588': 0.46765207079000176,
 '789': 0.46765207079000176,
 '792': 0.46765207079000176,
 '811': 0.46765207079000176,
 '649': 0.4674789304453924,
 '650': 0.4674789304453924,
 '665': 0.4674789304453924,
 '726': 0.4671330340854624,
 '778': 0.4671330340854624,
 '795': 0.4669602777858746,
 '1953': 0.4669602777858746,
 '733': 0.46627052848338435,
 '864': 0.46609840942525094,
 '1156': 0.46609840942525094,
 '1081': 0.4659264173922527,
 '111': 0.4657545522438232,
 '933': 0.4657545522438232,
 '978': 0.4657545522438232,
 '979': 0.4657545522438232,
 '1934': 0.4657545522438232,
 '1936': 0.4657545522438232,
 '1428': 0.4655828138396036,
 '1108': 0.46541120203944153,
 '1468': 0.46541120203944153,
 '1225': 0.46523971670339165,
 '1659': 0.46523971670339165,
 '1665': 0.46523971670339165,
 '809': 0.4650683576917145,
 '946': 0.4650683576917145,
 '1165': 0.4650683576917145,
 '794': 0.4648971248648766,
 '1784': 0.4648971248648766,
 '60': 0.4647260180835498,
 '61': 0.4647260180835498,
 '1030': 0.4647260180835498,
 '1044': 0.4647260180835498,
 '1051': 0.4647260180835498,
 '1062': 0.4647260180835498,
 '1064': 0.4647260180835498,
 '1104': 0.4647260180835498,
 '1125': 0.4647260180835498,
 '1133': 0.4647260180835498,
 '1307': 0.4647260180835498,
 '110': 0.4645550372086111,
 '1195': 0.4645550372086111,
 '1212': 0.4645550372086111,
 '1235': 0.4645550372086111,
 '1255': 0.4645550372086111,
 '1291': 0.4645550372086111,
 '1294': 0.4645550372086111,
 '1327': 0.4645550372086111,
 '1328': 0.4645550372086111,
 '1339': 0.4645550372086111,
 '208': 0.4643841821011419,
 '1421': 0.4643841821011419,
 '1474': 0.4643841821011419,
 '1735': 0.46404284863395984,
 '1743': 0.46404284863395984,
 '1369': 0.4638723699974302,
 '1515': 0.4635317882279753,
 '1566': 0.4635317882279753,
 '1567': 0.4635317882279753,
 '1576': 0.46336168481945134,
 '1693': 0.46336168481945134,
 '1696': 0.46336168481945134,
 '1539': 0.4631917062116672,
 '1650': 0.4631917062116672,
 '1651': 0.4631917062116672,
 '1654': 0.4631917062116672,
 '1655': 0.4631917062116672,
 '1505': 0.4630218522673285,
 '1047': 0.46285212284934196,
 '1424': 0.46268251782081526,
 '158': 0.46251303704505675,
 '1460': 0.46234368038557483,
 '1729': 0.46234368038557483,
 '1708': 0.4621744477060779,
 '1727': 0.4621744477060779,
 '1733': 0.4621744477060779,
 '1736': 0.4621744477060779,
 '1740': 0.4621744477060779,
 '1742': 0.4621744477060779,
 '251': 0.4620053388704738,
 '252': 0.4618363537428694,
 '357': 0.46166749218757036,
 '1779': 0.46133013925210264,
 '1895': 0.4611616476015358,
 '654': 0.4609932789824771,
 '1859': 0.4609932789824771,
 '1866': 0.4609932789824771,
 '1868': 0.4609932789824771,
 '296': 0.46082503326022073,
 '313': 0.46082503326022073,
 '734': 0.46082503326022073,
 '1161': 0.46082503326022073,
 '784': 0.4606569103002571,
 '1157': 0.4606569103002571,
 '752': 0.46048890996827313,
 '1295': 0.46048890996827313,
 '1941': 0.46032103213015124,
 '1970': 0.46032103213015124,
 '1982': 0.46032103213015124,
 '597': 0.46015327665196976,
 '793': 0.45998564340000175,
 '655': 0.45981813224071555,
 '1310': 0.45981813224071555,
 '1778': 0.45981813224071555,
 '1983': 0.45981813224071555,
 '428': 0.4596507430407735,
 '1366': 0.4596507430407735,
 '2025': 0.4596507430407735,
 '234': 0.4593163299865423,
 '240': 0.4591493058665472,
 '241': 0.4591493058665472,
 '274': 0.4591493058665472,
 '1879': 0.4591493058665472,
 '1930': 0.45881562177798135,
 '1023': 0.4586489615448619,
 '1661': 0.4586489615448619,
 '1766': 0.4586489615448619,
 '145': 0.458482422343139,
 '993': 0.45814970650689585,
 '1346': 0.4578174732171881,
 '1642': 0.4576515371993493,
 '874': 0.45748572142500177,
 '127': 0.45715445008436095,
 '1116': 0.45715445008436095,
 '1673': 0.45682365815231724,
 '1912': 0.45682365815231724,
 '0': 0.4566584416394231,
 '496': 0.4564933445889388,
 '497': 0.4564933445889388,
 '1048': 0.4564933445889388,
 '1086': 0.4564933445889388,
 '1260': 0.4564933445889388,
 '1804': 0.4564933445889388,
 '369': 0.45632836687134254,
 '549': 0.45632836687134254,
 '609': 0.45632836687134254,
 '802': 0.45632836687134254,
 '803': 0.45632836687134254,
 '1002': 0.45632836687134254,
 '295': 0.45599876891766156,
 '548': 0.45599876891766156,
 '1053': 0.45599876891766156,
 '1750': 0.4558341484234675,
 '207': 0.45566964674594185,
 '1790': 0.45566964674594185,
 '1972': 0.45566964674594185,
 '172': 0.45534099932672367,
 '320': 0.45534099932672367,
 '613': 0.45534099932672367,
 '1752': 0.45534099932672367,
 '1754': 0.45534099932672367,
 '1261': 0.4551768533284084,
 '645': 0.4548489161141948,
 '646': 0.4548489161141948,
 '118': 0.4546851246427817,
 '288': 0.4546851246427817,
 '799': 0.4546851246427817,
 '1357': 0.4546851246427817,
 '354': 0.454194457242088,
 '1194': 0.454194457242088,
 '1209': 0.454194457242088,
 '1214': 0.454194457242088,
 '1298': 0.45403113668932216,
 '471': 0.45386793354888744,
 '606': 0.45386793354888744,
 '1422': 0.45386793354888744,
 '1755': 0.45386793354888744,
 '491': 0.45370484769421665,
 '1473': 0.453379027336806,
 '1666': 0.453379027336806,
 '1632': 0.4532162925818395,
 '1644': 0.4532162925818395,
 '1645': 0.4532162925818395,
 '1262': 0.45289117329017387,
 '1763': 0.45289117329017387,
 '1918': 0.45289117329017387,
 '865': 0.45272878850233234,
 '1309': 0.45272878850233234,
 '281': 0.4525665201193566,
 '1801': 0.4525665201193566,
 '1874': 0.45224233206769515,
 '798': 0.45208041214930356,
 '1747': 0.45208041214930356,
 '1481': 0.4519186081363654,
 '1885': 0.4519186081363654,
 '1547': 0.45175691990447403,
 '1548': 0.45175691990447403,
 '624': 0.45159534732940093,
 '224': 0.451433890287095,
 '1668': 0.451433890287095,
 '342': 0.45111132230546797,
 '492': 0.45095021111893024,
 '1502': 0.45095021111893024,
 '965': 0.4507892149707265,
 '707': 0.4506283337376891,
 '1465': 0.4506283337376891,
 '361': 0.4504675672968266,
 '580': 0.4503069155253227,
 '1189': 0.4503069155253227,
 '1358': 0.4503069155253227,
 '731': 0.4501463783005365,
 '70': 0.4498256470014268,
 '71': 0.4498256470014268,
 '960': 0.4498256470014268,
 '453': 0.44950537242186006,
 '1803': 0.44950537242186006,
 '641': 0.4491855535869815,
 '758': 0.4490258147699164,
 '1882': 0.4490258147699164,
 '511': 0.4488661895247084,
 '638': 0.4488661895247084,
 '980': 0.4488661895247084,
 '360': 0.44870667773027895,
 '611': 0.4485472792657211,
 '1275': 0.4485472792657211,
 '1959': 0.4483879940103,
 '298': 0.4482288218434522,
 '1070': 0.4482288218434522,
 '1583': 0.4482288218434522,
 '1762': 0.4482288218434522,
 '519': 0.44806976264478526,
 '940': 0.44806976264478526,
 '1580': 0.44806976264478526,
 '1714': 0.44806976264478526,
 '1124': 0.4479108162940776,
 '1140': 0.4479108162940776,
 '1172': 0.4479108162940776,
 '1397': 0.44759326165650654,
 '1398': 0.44759326165650654,
 '1409': 0.44759326165650654,
 '1411': 0.44759326165650654,
 '1112': 0.4474346531300513,
 '656': 0.4472761569723715,
 '1229': 0.4472761569723715,
 '1382': 0.4472761569723715,
 '730': 0.4471177730640952,
 '926': 0.4471177730640952,
 '245': 0.44695950128601947,
 '1272': 0.44695950128601947,
 '1336': 0.44695950128601947,
 '427': 0.44680134151910994,
 '562': 0.44680134151910994,
 '1286': 0.4466432936445012,
 '1363': 0.4466432936445012,
 '239': 0.44648535754349533,
 '1350': 0.44648535754349533,
 '999': 0.44632753309756273,
 '1341': 0.44632753309756273,
 '1351': 0.44632753309756273,
 '1352': 0.44632753309756273,
 '1388': 0.44632753309756273,
 '1894': 0.44632753309756273,
 '1427': 0.44616982018834095,
 '1884': 0.4460122186976351,
 '512': 0.445854728507417,
 '883': 0.445854728507417,
 '1966': 0.445854728507417,
 '700': 0.44569734949982526,
 '994': 0.44554008155716474,
 '1293': 0.4453829245619065,
 '1278': 0.44506894294430904,
 '1787': 0.44506894294430904,
 '101': 0.44491211808773956,
 '833': 0.44491211808773956,
 '1024': 0.44491211808773956,
 '1080': 0.44491211808773956,
 '1960': 0.44491211808773956,
 '1113': 0.4447554037101109,
 '839': 0.4444423059250281,
 '1092': 0.4442859222846604,
 '1200': 0.44412964865740584,
 '1151': 0.4439734849272169,
 '1154': 0.4439734849272169,
 '2029': 0.4439734849272169,
 '1118': 0.4438174309782091,
 '217': 0.4436614866946609,
 '1129': 0.4436614866946609,
 '372': 0.4435056519610133,
 '1932': 0.4435056519610133,
 '1299': 0.4433499266618697,
 '773': 0.4431943106819954,
 '1021': 0.4431943106819954,
 '1022': 0.4431943106819954,
 '1687': 0.4431943106819954,
 '1710': 0.4431943106819954,
 '1987': 0.4431943106819954,
 '1640': 0.44303880390631745,
 '1325': 0.44288340621992456,
 '1469': 0.44288340621992456,
 '1470': 0.44288340621992456,
 '913': 0.44272811750806623,

### Centralidad de intermediación

In [35]:
dict(sorted(nx.betweenness_centrality(G).items(), key=lambda item: item[1], reverse=True))

{'22': 0.017202521003575957,
 '163': 0.01196116088011473,
 '401': 0.009608164369537762,
 '586': 0.009194835968725534,
 '84': 0.008760862751412652,
 '1507': 0.00839106652162111,
 '813': 0.00813839966023271,
 '956': 0.00731847977200845,
 '937': 0.007253605067141541,
 '954': 0.007181214912220725,
 '1343': 0.007045113625558695,
 '1344': 0.007045113625558695,
 '493': 0.005569417798462073,
 '1922': 0.004694776633801951,
 '1923': 0.004694776633801951,
 '1345': 0.00441897764992807,
 '82': 0.0043998123870765075,
 '162': 0.0038351870809035064,
 '1618': 0.003164696779987257,
 '85': 0.0031359204206239384,
 '399': 0.003011336778592275,
 '5': 0.0029997437481375303,
 '1927': 0.002747919541149772,
 '52': 0.0027089094667031638,
 '4': 0.0027068404480713143,
 '59': 0.0026090084575431517,
 '957': 0.0024822573916231916,
 '1876': 0.0022779883419744625,
 '1699': 0.002259407979593455,
 '155': 0.002165753126756275,
 '230': 0.0021513484199342093,
 '205': 0.0021393903147989015,
 '400': 0.002093535975818443,
 '1749': 0.002062080615899961,
 '297': 0.0020570154932114198,
 '315': 0.00202663246755851,
 '316': 0.00202663246755851,
 '319': 0.0020136172213077843,
 '1870': 0.001877509005817853,
 '783': 0.0018238212701061048,
 '955': 0.001813336487413177,
 '587': 0.001743580291098045,
 '402': 0.001675606390769764,
 '612': 0.0016593044088515452,
 '584': 0.001643221395862865,
 '1342': 0.0016137017241997548,
 '65': 0.0015747121526000906,
 '967': 0.001569042114709719,
 '1011': 0.001529801310554888,
 '1259': 0.0014521295736449012,
 '1931': 0.0014388650098663277,
 '774': 0.001412048065887202,
 '814': 0.0013729575932709844,
 '1163': 0.0013657891645167618,
 '1164': 0.0013657891645167618,
 '160': 0.001359462369009943,
 '1158': 0.001358537528495163,
 '1701': 0.0013507917806691986,
 '1101': 0.001347747194590388,
 '1680': 0.0013431761234919033,
 '398': 0.0013395421610687876,
 '1674': 0.0013346456930140407,
 '1753': 0.0013164999514338545,
 '1751': 0.0013101360737242929,
 '998': 0.001303801872999937,
 '585': 0.0012915012676479973,
 '1877': 0.001286512313691178,
 '1338': 0.001247319632975975,
 '1506': 0.001240546766918333,
 '1625': 0.0012375741145934538,
 '1627': 0.0012375741145934538,
 '1503': 0.001234275611653014,
 '878': 0.0012275332231726326,
 '1543': 0.0012152126251447058,
 '1544': 0.0012152126251447058,
 '1617': 0.0012145702495184485,
 '1584': 0.0012133940690705208,
 '919': 0.0011980613282454792,
 '1652': 0.001186177808942697,
 '1653': 0.001186177808942697,
 '1662': 0.001186177808942697,
 '1663': 0.001186177808942697,
 '311': 0.0011798993955667385,
 '1756': 0.00117326051480675,
 '113': 0.001163473016926366,
 '1937': 0.0011501115627255548,
 '102': 0.0011466425213620174,
 '1540': 0.0011436647723574245,
 '1541': 0.0011436647723574245,
 '990': 0.0011308462898173889,
 '1497': 0.001115826685742388,
 '441': 0.0010899711123352061,
 '1029': 0.0010832038358630643,
 '70': 0.0010733289502267622,
 '71': 0.0010733289502267622,
 '1052': 0.0010707668828683278,
 '1091': 0.0010560189737494096,
 '1126': 0.0010496811317486318,
 '1119': 0.0010423789176935304,
 '785': 0.0010170446593205061,
 '159': 0.001000564236545001,
 '173': 0.001000564236545001,
 '806': 0.0009975652142105698,
 '1269': 0.000899162558391264,
 '1276': 0.000899162558391264,
 '1335': 0.0008824317768938072,
 '53': 0.0008659367183724765,
 '1381': 0.0008251408612117344,
 '1423': 0.0008234929862930354,
 '1425': 0.0008234929862930354,
 '280': 0.0008125122838356314,
 '1450': 0.0008123352739740867,
 '1461': 0.0008053883224442916,
 '1176': 0.0008052224224487282,
 '1177': 0.0008052224224487282,
 '1178': 0.0008052224224487282,
 '356': 0.0007932208201472847,
 '358': 0.0007932208201472847,
 '1128': 0.0007846781721024792,
 '100': 0.0007689556485574867,
 '6': 0.0007599515748451423,
 '1590': 0.0007597115764765801,
 '1592': 0.0007597115764765801,
 '879': 0.0007593001171702637,
 '1641': 0.0007569407355938997,
 '1667': 0.0007569407355938997,
 '1777': 0.0007501266074032924,
 '804': 0.0007487189350225917,
 '764': 0.0007442619461243276,
 '767': 0.0007442619461243276,
 '1445': 0.0007294912402446544,
 '1438': 0.0007275179146811725,
 '918': 0.0007273613464888316,
 '1429': 0.0007179846018689514,
 '1538': 0.0007164019765157324,
 '129': 0.0007147959724291981,
 '1781': 0.0007133526954997312,
 '1772': 0.0007085948912771454,
 '1776': 0.0007085948912771454,
 '1806': 0.0007085948912771454,
 '1880': 0.0007002718063292723,
 '1883': 0.0007002718063292723,
 '423': 0.0006937508050934116,
 '66': 0.0006905615507397636,
 '299': 0.0006903532517751994,
 '178': 0.0006894531519515381,
 '1764': 0.0006872763772125593,
 '1608': 0.0006776864435448744,
 '1615': 0.0006775775088017163,
 '991': 0.0006770307042798726,
 '50': 0.0006758810639631979,
 '1935': 0.0006712074971867669,
 '1955': 0.0006693763392313437,
 '1961': 0.0006693763392313437,
 '454': 0.0006669940922896041,
 '472': 0.0006669940922896041,
 '520': 0.0006669940922896041,
 '521': 0.0006669940922896041,
 '522': 0.0006669940922896041,
 '596': 0.0006669940922896041,
 '1971': 0.0006473600305667826,
 '631': 0.0006451144130263863,
 '811': 0.0006419538501323846,
 '1700': 0.0006387343871159043,
 '637': 0.000635706613775524,
 '1068': 0.0006331883500263515,
 '1127': 0.0006331883500263515,
 '651': 0.0006323789014795532,
 '653': 0.0006323789014795532,
 '662': 0.0006323789014795532,
 '1826': 0.0006270415122596713,
 '729': 0.0006237049148312043,
 '732': 0.0006237049148312043,
 '809': 0.0006186620805148598,
 '513': 0.0006157789290138716,
 '514': 0.0006157789290138716,
 '930': 0.0006137934269411268,
 '740': 0.0006124396343340006,
 '741': 0.0006124396343340006,
 '751': 0.0006124396343340006,
 '800': 0.0006124396343340006,
 '69': 0.0006004185029668135,
 '90': 0.0005872718770773644,
 '91': 0.0005872718770773644,
 '840': 0.0005855382061999752,
 '1953': 0.0005769327537726877,
 '119': 0.000576261768019955,
 '572': 0.0005655310632726791,
 '574': 0.0005655310632726791,
 '1766': 0.0005627520627100259,
 '1162': 0.0005622020016974221,
 '1270': 0.0005600970897478496,
 '144': 0.0005598588303858378,
 '243': 0.0005598588303858378,
 '244': 0.0005598588303858378,
 '253': 0.0005585461224500612,
 '786': 0.0005578881772240572,
 '314': 0.000550614975634962,
 '986': 0.0005399939230587105,
 '987': 0.0005399939230587105,
 '992': 0.0005399939230587105,
 '0': 0.0005371861469523013,
 '1684': 0.0005313038908353307,
 '48': 0.0005283705090676685,
 '287': 0.0005249292485213744,
 '1026': 0.0005220660277449152,
 '1049': 0.0005220660277449152,
 '1077': 0.0005220660277449152,
 '1082': 0.0005220660277449152,
 '1084': 0.0005220660277449152,
 '204': 0.0005213163362567919,
 '292': 0.0005209015669964859,
 '294': 0.0005209015669964859,
 '802': 0.0005155144752666292,
 '803': 0.0005155144752666292,
 '1109': 0.000511060898889176,
 '1110': 0.000511060898889176,
 '1114': 0.000511060898889176,
 '1433': 0.0005041889342918173,
 '779': 0.0005002346742772395,
 '1570': 0.0004986876104616278,
 '1673': 0.0004969902280881187,
 '301': 0.0004935943623189877,
 '1549': 0.0004917350806943456,
 '227': 0.000490962233177908,
 '2009': 0.0004907086819580544,
 '187': 0.00048202482956680816,
 '1982': 0.0004783910266744521,
 '1941': 0.0004735998528762316,
 '60': 0.00046564616604101254,
 '61': 0.00046564616604101254,
 '1357': 0.0004609798727141326,
 '362': 0.00045733056532129627,
 '1161': 0.0004534068297197286,
 '416': 0.00044568056827950614,
 '1782': 0.0004455999724667609,
 '1802': 0.000441777215271737,
 '110': 0.00044076348705750023,
 '1400': 0.0004402963215855148,
 '38': 0.0004346800726261931,
 '1310': 0.0004344980493811782,
 '1930': 0.0004247914499183516,
 '425': 0.00042286295846618476,
 '111': 0.0004214253767073435,
 '1262': 0.0004203494392956928,
 '439': 0.00042011905228969557,
 '88': 0.00041856154005359225,
 '1376': 0.0004181392111660043,
 '940': 0.00041713893728906743,
 '1958': 0.0004166851335184547,
 '49': 0.0004108160821170248,
 '482': 0.0004101361985099139,
 '483': 0.0004101361985099139,
 '529': 0.0004101361985099139,
 '112': 0.0004049837323175158,
 '1007': 0.0004027724374140671,
 '796': 0.00040226216187747406,
 '876': 0.0003862005249932777,
 '882': 0.0003862005249932777,
 '1023': 0.0003852636812775668,
 '1827': 0.0003836296385986722,
 '560': 0.0003823700232706553,
 '567': 0.0003823700232706553,
 '757': 0.00037876587847767335,
 '1111': 0.00037275340119238864,
 '510': 0.0003710751528181144,
 '1446': 0.00037025042952432044,
 '1447': 0.00037025042952432044,
 '1462': 0.00037025042952432044,
 '1463': 0.00037025042952432044,
 '1467': 0.00037025042952432044,
 '1480': 0.00037025042952432044,
 '1487': 0.00037025042952432044,
 '117': 0.0003685300572343144,
 '122': 0.0003685300572343144,
 '1805': 0.00036743844932172993,
 '616': 0.0003671623783674434,
 '674': 0.0003667573503646369,
 '968': 0.0003663495666081648,
 '1878': 0.00036161805411209633,
 '234': 0.0003613764068268163,
 '1088': 0.00035964358282724267,
 '1712': 0.00035822259547335135,
 '1532': 0.0003574589106364477,
 '240': 0.00035723520189521194,
 '241': 0.00035723520189521194,
 '274': 0.00035723520189521194,
 '1790': 0.0003550944407020696,
 '245': 0.00035289059002684684,
 '1444': 0.00035150413282983767,
 '1504': 0.00035150413282983767,
 '1912': 0.00035047925245504174,
 '208': 0.000345518396104187,
 '296': 0.0003443651102003503,
 '313': 0.0003443651102003503,
 '1358': 0.0003434477812652936,
 '1934': 0.0003430797286268723,
 '1936': 0.0003430797286268723,
 '1405': 0.0003416727156049179,
 '888': 0.00033244318189610097,
 '832': 0.00033103430623457114,
 '867': 0.0003300129277553527,
 '908': 0.0003300129277553527,
 '379': 0.0003299129131343047,
 '1672': 0.00032853673719702596,
 '158': 0.00032760040400405823,
 '1933': 0.0003271653249259685,
 '320': 0.00032242441369631963,
 '856': 0.0003211995033920859,
 '1074': 0.0003210261825122104,
 '705': 0.0003204252950369158,
 '1419': 0.00031997510856264424,
 '295': 0.0003165503218064429,
 '1583': 0.00031385360189035554,
 '302': 0.0003135174066977339,
 '571': 0.00031137528612328584,
 '953': 0.00031052269887969536,
 '868': 0.000310150013255315,
 '884': 0.000310150013255315,
 '885': 0.000310150013255315,
 '898': 0.000310150013255315,
 '900': 0.000310150013255315,
 '901': 0.000310150013255315,
 '1666': 0.0003100318930694223,
 '496': 0.0003085323249711065,
 '497': 0.0003085323249711065,
 '733': 0.00030815940663255994,
 '788': 0.00030731271835974177,
 '791': 0.00030731271835974177,
 '1632': 0.0003071371001261037,
 '1644': 0.0003071371001261037,
 '1645': 0.0003071371001261037,
 '801': 0.00030403620552858817,
 '369': 0.00030223741857155254,
 '1010': 0.0002988194797255514,
 '548': 0.0002965739965925052,
 '1054': 0.00029639706730860205,
 '1056': 0.00029639706730860205,
 '207': 0.00029598240431693326,
 '925': 0.0002959043163261641,
 '281': 0.00029551629993848725,
 '1499': 0.0002945992460436946,
 '1835': 0.0002944276121479922,
 '1836': 0.0002944276121479922,
 '1076': 0.0002941034600973808,
 '1120': 0.0002930824753616318,
 '1872': 0.0002928191480934759,
 '370': 0.0002912378379351295,
 '1303': 0.00029109540207244327,
 '1899': 0.00029057302344169484,
 '1919': 0.00029057302344169484,
 '1921': 0.00029057302344169484,
 '1687': 0.0002900746799515647,
 '958': 0.000288871621601682,
 '1547': 0.00028820467938565485,
 '1548': 0.00028820467938565485,
 '357': 0.0002872894975267246,
 '613': 0.00028609670367304963,
 '1967': 0.0002851243612324653,
 '2002': 0.0002834034086836999,
 '1228': 0.0002830975764505545,
 '1230': 0.0002830975764505545,
 '1860': 0.0002800982841908807,
 '1004': 0.0002798278286875412,
 '1005': 0.0002798278286875412,
 '645': 0.00027869555487964747,
 '646': 0.00027869555487964747,
 '805': 0.0002785879222048212,
 '1028': 0.0002779935752707658,
 '1043': 0.0002779935752707658,
 '1502': 0.0002772815534230273,
 '839': 0.00027523521569851583,
 '1309': 0.00027302287122971895,
 '1337': 0.00027246834502622026,
 '980': 0.0002705101471083906,
 '1190': 0.0002703908208767049,
 '1216': 0.00026872652880710493,
 '63': 0.0002665892725213823,
 '1770': 0.00026613344705694327,
 '1807': 0.00026613344705694327,
 '1282': 0.0002652284685181282,
 '1047': 0.00026001753366929113,
 '1845': 0.00025896754134307234,
 '1370': 0.00025834149993404093,
 '822': 0.0002578271790954386,
 '960': 0.00025672609780515984,
 '1173': 0.00025654395020862313,
 '1175': 0.00025654395020862313,
 '1081': 0.0002563002340304944,
 '1306': 0.0002562686823092534,
 '1654': 0.00025482854461548955,
 '1489': 0.00025413664089437866,
 '1490': 0.00025413664089437866,
 '1493': 0.00025413664089437866,
 '1494': 0.00025413664089437866,
 '704': 0.00025312151186053554,
 '1200': 0.00025230513933370373,
 '1498': 0.00025200221906047937,
 '1611': 0.0002514383614541188,
 '1848': 0.0002502464629743483,
 '250': 0.000249936077984649,
 '1793': 0.0002481336655276728,
 '1938': 0.00024730527378208036,
 '1968': 0.00024724559504880753,
 '1021': 0.00024718000149059546,
 '1022': 0.00024718000149059546,
 '853': 0.0002457028608952669,
 '1292': 0.00024518598805252405,
 '1324': 0.00024518598805252405,
 '952': 0.00024387004830872836,
 '1750': 0.00024346398948838115,
 '931': 0.0002428814653295022,
 '932': 0.0002428814653295022,
 '1950': 0.0002428814653295022,
 '1397': 0.00024220660504166284,
 '1398': 0.00024220660504166284,
 '1409': 0.00024220660504166284,
 '1411': 0.00024220660504166284,
 '1395': 0.00024064428268651095,
 '1396': 0.00024064428268651095,
 '1365': 0.00024022852574552228,
 '1382': 0.00023893377719004077,
 '1942': 0.00023763451908049516,
 '1943': 0.00023763451908049516,
 '1500': 0.00023451264067536766,
 '1579': 0.00023417043511743616,
 '1581': 0.00023417043511743616,
 '1587': 0.00023417043511743616,
 '1622': 0.00023417043511743616,
 '1682': 0.00023417043511743616,
 '1715': 0.00023417043511743616,
 '1716': 0.00023417043511743616,
 '1748': 0.00023417043511743616,
 '1940': 0.00023356943547898408,
 '251': 0.00023347741917808753,
 '1075': 0.0002333113117823186,
 '1424': 0.000232923445645764,
 '1726': 0.00023263113555173625,
 '1728': 0.00023263113555173625,
 '1732': 0.00023263113555173625,
 '1741': 0.00023263113555173625,
 '655': 0.00023230046175468774,
 '1451': 0.00023223474176573976,
 '1452': 0.00023223474176573976,
 '1596': 0.00023212538787527228,
 '1598': 0.00023212538787527228,
 '1698': 0.00023212538787527228,
 '3': 0.0002316712342171566,
 '36': 0.0002316712342171566,
 '62': 0.0002316712342171566,
 '1760': 0.0002309447066996997,
 '1785': 0.00023081818779373896,
 '1808': 0.00023081818779373896,
 '1837': 0.00023081818779373896,
 '64': 0.00023075603842053573,
 '1891': 0.00023036223300021836,
 '1892': 0.00023036223300021836,
 '1341': 0.0002295545049791458,
 '1351': 0.0002295545049791458,
 '1352': 0.0002295545049791458,
 '1812': 0.00022878942900394784,
 '766': 0.00022836996348569256,
 '354': 0.0002283230057229096,
 '1145': 0.0002277795937545716,
 '298': 0.0002275470922336765,
 '1460': 0.00022727703137242792,
 '1994': 0.00022647577227790752,
 '2014': 0.0002258930688122431,
 '641': 0.00022485881136454286,
 '209': 0.00022472960770429117,
 '210': 0.00022472960770429117,
 '211': 0.00022472960770429117,
 '597': 0.0002234254154550966,
 '89': 0.00022083313093637682,
 '1174': 0.00022045675491530963,
 '1745': 0.00022017436536239177,
 '1986': 0.00021921565714702964,
 '1809': 0.00021669560554508406,
 '83': 0.00021572591864327346,
 '239': 0.00021485910904333396,
 '1336': 0.00021361862187101828,
 '654': 0.0002133619577015109,
 '1626': 0.00021229998436210468,
 '1053': 0.00021216199671197743,
 '734': 0.0002110456136133531,
 '1628': 0.0002104870515109605,
 '1151': 0.00020915624582208136,
 '1154': 0.00020915624582208136,
 '1159': 0.00020857982681523658,
 '1906': 0.00020750499721916107,
 '1129': 0.00020654776544636803,
 '1642': 0.00020636835272366203,
 '1578': 0.00020576204003440536,
 '752': 0.0002044294773642896,
 '588': 0.0002041793210237703,
 '1874': 0.00020180068309152453,
 '1032': 0.00019986413638822817,
 '1969': 0.0001980738519252095,
 '1430': 0.0001979148237443464,
 '1763': 0.00019737277230201582,
 '176': 0.00019660819968041367,
 '177': 0.00019660819968041367,
 '1879': 0.00019618525127328674,
 '2021': 0.00019533375568360156,
 '1403': 0.00019531494746269715,
 '787': 0.00019491674782294775,
 '790': 0.00019491674782294775,
 '252': 0.00019451814075106783,
 '1804': 0.00019373371068458057,
 '1048': 0.00019368046495280792,
 '1086': 0.00019368046495280792,
 '1762': 0.00019271643442232605,
 '8': 0.00019239635475617765,
 '140': 0.00019239635475617765,
 '164': 0.00019239635475617765,
 '285': 0.00019239635475617765,
 '286': 0.00019239635475617765,
 '418': 0.00019239635475617765,
 '463': 0.00019239635475617765,
 '599': 0.00019239635475617765,
 '699': 0.00019239635475617765,
 '771': 0.00019239635475617765,
 '772': 0.00019239635475617765,
 '939': 0.000192315960688324,
 '108': 0.00019229366147571398,
 '109': 0.00019229366147571398,
 '795': 0.00019041430811785854,
 '821': 0.0001899348219558063,
 '1595': 0.00018938105535590583,
 '789': 0.00018813682235462904,
 '792': 0.00018813682235462904,
 '874': 0.0001875290651835689,
 '1734': 0.00018629373413212095,
 '1744': 0.00018629373413212095,
 '920': 0.00018579415749091056,
 '921': 0.00018579415749091056,
 '922': 0.00018579415749091056,
 '924': 0.00018579415749091056,
 '101': 0.00018558123633477454,
 '913': 0.0001851976719808829,
 '1437': 0.0001832676039783712,
 '794': 0.00018167220626653667,
 '993': 0.00018125764202298056,
 '1124': 0.00018082122751252294,
 '1140': 0.00018082122751252294,
 '881': 0.00017956083195010868,
 '1757': 0.00017865887073574387,
 '145': 0.00017840872601003596,
 '905': 0.00017698602384455875,
 '929': 0.00017698602384455875,
 '389': 0.00017682408163226484,
 '391': 0.00017682408163226484,
 '392': 0.00017682408163226484,
 '1844': 0.00017674888410712788,
 '864': 0.0001762091600425342,
 '127': 0.00017563798452752756,
 '1758': 0.0001756296131345732,
 '1002': 0.00017504143952463085,
 '798': 0.00017378014570371936,
 '799': 0.00017327407259739054,
 '703': 0.00017308897418063886,
 '642': 0.00017278828953592112,
 '300': 0.00017267170264450253,
 '1609': 0.00017172306298630336,
 '1801': 0.0001715327255628991,
 '471': 0.0001703787038875607,
 '1116': 0.00016963662414785254,
 '118': 0.00016810122391646847,
 '636': 0.0001676138506286556,
 '157': 0.00016760161857059895,
 '1885': 0.00016756411887106188,
 '1156': 0.00016713329180656069,
 '330': 0.00016623301315768182,
 '1165': 0.00016524074371201985,
 '1160': 0.00016488124903146352,
 '1008': 0.00016430409047711098,
 '1009': 0.00016430409047711098,
 '168': 0.00016361664478384302,
 '170': 0.00016361664478384302,
 '278': 0.00016361664478384302,
 '154': 0.0001635536103339774,
 '462': 0.0001635536103339774,
 '564': 0.0001635536103339774,
 '696': 0.0001635536103339774,
 '1304': 0.0001633278346786631,
 '619': 0.0001628985012527641,
 '942': 0.00016240944343471258,
 '1112': 0.00016146937442051664,
 '450': 0.0001594418383320445,
 '486': 0.0001594418383320445,
 '1092': 0.00015896262481209184,
 '380': 0.00015877666159014577,
 '1297': 0.000158456948480121,
 '141': 0.00015838893159841056,
 '148': 0.00015838893159841056,
 '149': 0.00015838893159841056,
 '216': 0.00015838893159841056,
 '218': 0.00015838893159841056,
 '220': 0.00015838893159841056,
 '225': 0.00015838893159841056,
 '257': 0.00015838893159841056,
 '261': 0.00015838893159841056,
 '262': 0.00015838893159841056,
 '266': 0.00015838893159841056,
 '270': 0.00015838893159841056,
 '271': 0.00015838893159841056,
 '289': 0.00015838893159841056,
 '784': 0.0001583018153981792,
 '360': 0.00015739348408698437,
 '1293': 0.0001573220589726639,
 '962': 0.00015632794304718217,
 '422': 0.00015439866625862925,
 '793': 0.00015435911002146502,
 '337': 0.00015426884464288346,
 '344': 0.00015426884464288346,
 '371': 0.00015426884464288346,
 '373': 0.00015426884464288346,
 '417': 0.00015426884464288346,
 '447': 0.00015426884464288346,
 '526': 0.00015426884464288346,
 '527': 0.00015426884464288346,
 '543': 0.00015426884464288346,
 '544': 0.00015426884464288346,
 '545': 0.00015426884464288346,
 '558': 0.00015426884464288346,
 '578': 0.00015426884464288346,
 '590': 0.00015426884464288346,
 '626': 0.00015426884464288346,
 '1803': 0.00015409547587206762,
 '303': 0.0001535580420289391,

### PageRank

In [36]:
dict(sorted(nx.pagerank(G).items(), key=lambda item: item[1], reverse=True))

{'22': 0.001994732097235599,
 '163': 0.0019051746857167494,
 '401': 0.0018249687330944462,
 '586': 0.0018041264802592166,
 '813': 0.0017620168142773336,
 '937': 0.0017003674276199969,
 '956': 0.001699848390175887,
 '954': 0.001693766279801153,
 '84': 0.00164489508836549,
 '1507': 0.0015758432253696274,
 '493': 0.0015020229218979937,
 '1922': 0.0014816151474145469,
 '1923': 0.0014816151474145469,
 '1343': 0.0014663067624930781,
 '1344': 0.0014663067624930781,
 '5': 0.0013365792592136816,
 '4': 0.0012998686224948506,
 '1618': 0.0012857450253015784,
 '155': 0.0012718650634735017,
 '783': 0.0012631273402039676,
 '587': 0.001248143141435022,
 '82': 0.0012422010175127671,
 '162': 0.0012418348984005283,
 '280': 0.0012379625227799023,
 '1876': 0.0012228539154237061,
 '1345': 0.0012159548571475211,
 '967': 0.001207199802184982,
 '52': 0.0012067490822543936,
 '59': 0.0012020969089143402,
 '1259': 0.0012019433607791102,
 '1011': 0.001200420186618664,
 '764': 0.0011918896341079456,
 '767': 0.0011918896341079456,
 '1163': 0.0011905989328361555,
 '1164': 0.0011905989328361555,
 '399': 0.0011904310668453787,
 '1158': 0.001187996472152846,
 '1749': 0.0011714953210688545,
 '1101': 0.0011700150462172047,
 '572': 0.001169844027317335,
 '574': 0.001169844027317335,
 '230': 0.0011676053565492133,
 '1753': 0.0011634485929156416,
 '1751': 0.0011621250354733527,
 '1680': 0.0011617482348732593,
 '1506': 0.0011609517460413107,
 '1503': 0.001159628188599022,
 '297': 0.0011570442550245291,
 '1927': 0.0011558131915938238,
 '315': 0.0011539487388271504,
 '316': 0.0011539487388271504,
 '1617': 0.0011539262477283192,
 '205': 0.0011534895192258743,
 '319': 0.0011520554140156028,
 '1338': 0.0011487714395762272,
 '1590': 0.0011482210030960298,
 '1592': 0.0011482210030960298,
 '957': 0.001143335333342166,
 '1543': 0.0011410999663935824,
 '1544': 0.0011410999663935824,
 '1584': 0.0011399910797120975,
 '1756': 0.001139523150058921,
 '779': 0.0011363382814638552,
 '1652': 0.0011340995498401482,
 '1653': 0.0011340995498401482,
 '1662': 0.0011340995498401482,
 '1663': 0.0011340995498401482,
 '930': 0.0011325215364729612,
 '1937': 0.0011262848876613767,
 '65': 0.0011128295068320645,
 '85': 0.0011022330705543317,
 '612': 0.0010990529139556944,
 '1699': 0.0010765801530068261,
 '204': 0.0010686730203323222,
 '441': 0.001064504157736462,
 '774': 0.0010606789484080385,
 '785': 0.0010606320602053478,
 '227': 0.0010429267636273643,
 '806': 0.0010388194571047912,
 '400': 0.0010289225270938144,
 '90': 0.0010283460157772247,
 '91': 0.0010283460157772247,
 '919': 0.0010258538441163699,
 '1877': 0.0010221851520991713,
 '878': 0.0010216149596074934,
 '990': 0.0010103763473107627,
 '510': 0.0010099065684594892,
 '955': 0.0010069014508760634,
 '1029': 0.0010007335015207069,
 '1052': 0.0009980457858085028,
 '1091': 0.0009950713417687012,
 '1126': 0.0009935550087456482,
 '1128': 0.0009903852763977184,
 '1712': 0.000988913003272817,
 '1445': 0.0009883958239508012,
 '1119': 0.000987923184783039,
 '1429': 0.0009862918679175146,
 '1870': 0.0009794340713805197,
 '1499': 0.0009780450483354971,
 '856': 0.0009764008226060096,
 '160': 0.0009755243091763363,
 '1764': 0.0009707905677627544,
 '1931': 0.0009673033089375752,
 '311': 0.000956428440848201,
 '1269': 0.0009549856288547017,
 '1276': 0.0009549856288547017,
 '1770': 0.000953604081684203,
 '1807': 0.000953604081684203,
 '1971': 0.0009526200478090329,
 '402': 0.0009440698813958091,
 '1532': 0.0009406350969273345,
 '584': 0.0009362254872674824,
 '1405': 0.0009330073179116642,
 '1423': 0.0009315735565194422,
 '1425': 0.0009315735565194422,
 '1450': 0.0009288056553513872,
 '571': 0.0009277964871518167,
 '1461': 0.0009271976292173086,
 '1674': 0.0009187297000048227,
 '804': 0.0009142088063532397,
 '1641': 0.0009114683472331187,
 '1667': 0.0009114683472331187,
 '102': 0.0009051628511977015,
 '1625': 0.0009024797547156292,
 '1627': 0.0009024797547156292,
 '8': 0.0009004063128202865,
 '140': 0.0009004063128202865,
 '164': 0.0009004063128202865,
 '285': 0.0009004063128202865,
 '286': 0.0009004063128202865,
 '418': 0.0009004063128202865,
 '463': 0.0009004063128202865,
 '599': 0.0009004063128202865,
 '699': 0.0009004063128202865,
 '771': 0.0009004063128202865,
 '772': 0.0009004063128202865,
 '1781': 0.0008964489226906628,
 '1772': 0.0008951253652483738,
 '1776': 0.0008951253652483738,
 '1806': 0.0008951253652483738,
 '113': 0.0008931644739052875,
 '159': 0.000892380414138157,
 '173': 0.000892380414138157,
 '1880': 0.0008904778259083177,
 '1883': 0.0008904778259083177,
 '1303': 0.0008864721224251854,
 '1540': 0.0008858398995572608,
 '1541': 0.0008858398995572608,
 '53': 0.0008855193525098917,
 '1701': 0.0008838479129489067,
 '1497': 0.0008790259495887066,
 '1955': 0.0008780622044002864,
 '1961': 0.0008780622044002864,
 '1162': 0.0008732606210772409,
 '356': 0.000872092107685412,
 '358': 0.000872092107685412,
 '1860': 0.0008710452602716601,
 '998': 0.000870622439363245,
 '6': 0.0008694421555884044,
 '879': 0.0008691835290122824,
 '814': 0.0008672640542867955,
 '1007': 0.0008632209253056016,
 '918': 0.000861186158476288,
 '585': 0.0008609955225365271,
 '66': 0.0008608312125867018,
 '423': 0.0008606839027601651,
 '786': 0.0008587047554410754,
 '154': 0.0008585970635681026,
 '462': 0.0008585970635681026,
 '564': 0.0008585970635681026,
 '696': 0.0008585970635681026,
 '454': 0.0008573685385548236,
 '472': 0.0008573685385548236,
 '520': 0.0008573685385548236,
 '521': 0.0008573685385548236,
 '522': 0.0008573685385548236,
 '596': 0.0008573685385548236,
 '631': 0.0008529068325074709,
 '1845': 0.0008527235257616646,
 '1335': 0.0008505970078854253,
 '637': 0.0008502272561936641,
 '651': 0.0008489601422717682,
 '653': 0.0008489601422717682,
 '662': 0.0008489601422717682,
 '991': 0.0008469871208363084,
 '1297': 0.0008464151111313386,
 '729': 0.0008462172408428647,
 '732': 0.0008462172408428647,
 '50': 0.000843411802709565,
 '740': 0.000843324585697783,
 '741': 0.000843324585697783,
 '751': 0.000843324585697783,
 '800': 0.000843324585697783,
 '119': 0.0008431582695970295,
 '144': 0.000840771823712931,
 '243': 0.000840771823712931,
 '244': 0.000840771823712931,
 '1521': 0.0008402713286662979,
 '1342': 0.0008397334848596023,
 '903': 0.0008386812341609422,
 '1068': 0.0008356775616653406,
 '1127': 0.0008356775616653406,
 '1202': 0.000833844287541644,
 '1234': 0.000833844287541644,
 '292': 0.0008317553770382536,
 '294': 0.0008317553770382536,
 '1145': 0.0008299297240983005,
 '513': 0.000825155828545434,
 '514': 0.000825155828545434,
 '398': 0.0008240959310964362,
 '301': 0.000817490258098389,
 '1381': 0.0008174208924249829,
 '986': 0.0008163852514465566,
 '987': 0.0008163852514465566,
 '992': 0.0008163852514465566,
 '287': 0.0008129826786765306,
 '416': 0.0008103727971103763,
 '1270': 0.0008099192412228694,
 '1026': 0.0008097652525161926,
 '1049': 0.0008097652525161926,
 '1077': 0.0008097652525161926,
 '1082': 0.0008097652525161926,
 '1084': 0.0008097652525161926,
 '1454': 0.0008095578487889961,
 '796': 0.0008094850010021013,
 '362': 0.0008077914761266898,
 '1109': 0.0008056779046916815,
 '1110': 0.0008056779046916815,
 '1114': 0.0008056779046916815,
 '1825': 0.0008052751198296977,
 '1826': 0.000803084462535779,
 '1935': 0.0008002575869264591,
 '482': 0.0007996681991074287,
 '483': 0.0007996681991074287,
 '529': 0.0007996681991074287,
 '1595': 0.0007990551154051189,
 '1176': 0.0007982287040344103,
 '1177': 0.0007982287040344103,
 '1178': 0.0007982287040344103,
 '425': 0.0007974312356128008,
 '363': 0.0007973308999557221,
 '364': 0.0007973308999557221,
 '2016': 0.0007973308999557221,
 '2030': 0.0007973308999557221,
 '766': 0.0007967938087569959,
 '439': 0.0007961076781705119,
 '178': 0.0007933696527833221,
 '1444': 0.0007913428948300948,
 '1504': 0.0007913428948300948,
 '717': 0.0007903513482260745,
 '718': 0.0007903513482260745,
 '720': 0.0007903513482260745,
 '1433': 0.0007877080329933223,
 '757': 0.0007868433685829679,
 '100': 0.0007854032284038584,
 '560': 0.0007849158159428115,
 '567': 0.0007849158159428115,
 '968': 0.0007836117672194124,
 '920': 0.0007832387553971305,
 '921': 0.0007832387553971305,
 '922': 0.0007832387553971305,
 '924': 0.0007832387553971305,
 '1538': 0.0007825220348383391,
 '1549': 0.0007813814100405807,
 '1438': 0.0007800287260254944,
 '674': 0.000779057664238856,
 '616': 0.0007771423034496731,
 '881': 0.0007745215655607202,
 '1933': 0.0007715452412349131,
 '888': 0.000770215814876596,
 '619': 0.0007700549938948582,
 '867': 0.0007688922574343071,
 '908': 0.0007688922574343071,
 '1615': 0.0007675234984106206,
 '953': 0.0007656202855314477,
 '112': 0.0007654751543432567,
 '832': 0.0007640033778593309,
 '1608': 0.0007632571693412989,
 '1376': 0.0007630728317722984,
 '1419': 0.000762136607593826,
 '1782': 0.0007620278598118975,
 '1802': 0.0007607043023696086,
 '1403': 0.0007601419799895405,
 '299': 0.0007600643397177613,
 '1401': 0.0007596814311755823,
 '1306': 0.0007567873320234599,
 '868': 0.0007559506959367317,
 '884': 0.0007559506959367317,
 '885': 0.0007559506959367317,
 '898': 0.0007559506959367317,
 '900': 0.0007559506959367317,
 '901': 0.0007559506959367317,
 '1074': 0.0007553940021820214,
 '48': 0.0007552270568841703,
 '1010': 0.0007534197948256868,
 '1054': 0.0007521796724803915,
 '1056': 0.0007521796724803915,
 '2009': 0.0007511925232930255,
 '1076': 0.0007508561150381026,
 '1120': 0.0007506633394573385,
 '1684': 0.0007493949967621889,
 '925': 0.0007484910370489852,
 '63': 0.0007479948082361422,
 '1337': 0.000747700559051678,
 '905': 0.0007472536083245791,
 '929': 0.0007472536083245791,
 '1198': 0.0007467819835361357,
 '1958': 0.0007461570795037594,
 '958': 0.000744824874653778,
 '1228': 0.0007444096827388317,
 '1230': 0.0007444096827388317,
 '1446': 0.0007420831869563295,
 '1447': 0.0007420831869563295,
 '1462': 0.0007420831869563295,
 '1463': 0.0007420831869563295,
 '1467': 0.0007420831869563295,
 '1480': 0.0007420831869563295,
 '1487': 0.0007420831869563295,
 '788': 0.0007420485306550573,
 '791': 0.0007420485306550573,
 '1004': 0.0007404782333281112,
 '1005': 0.0007404782333281112,
 '1321': 0.0007399750262231684,
 '1028': 0.0007392787118104421,
 '1043': 0.0007392787118104421,
 '209': 0.0007388002500927104,
 '210': 0.0007388002500927104,
 '211': 0.0007388002500927104,
 '1777': 0.0007367661017753052,
 '1726': 0.0007366091150103385,
 '1728': 0.0007366091150103385,
 '1732': 0.0007366091150103385,
 '1741': 0.0007366091150103385,
 '1190': 0.0007352396551075612,
 '1282': 0.000733867626111409,
 '38': 0.0007292049208476454,
 '253': 0.0007283325491399377,
 '310': 0.0007279213561928784,
 '89': 0.0007271519370260399,
 '1370': 0.0007267171661545442,
 '314': 0.0007265309410034777,
 '1570': 0.0007256683262443546,
 '88': 0.0007250641637901674,
 '1316': 0.00072468604942504,
 '1968': 0.0007245019984949872,
 '1489': 0.000724105096553956,
 '1490': 0.000724105096553956,
 '1493': 0.000724105096553956,
 '1494': 0.000724105096553956,
 '187': 0.0007235199752292119,
 '1498': 0.0007227815391116671,
 '1173': 0.000721390950999133,
 '1175': 0.000721390950999133,
 '876': 0.0007199841260368861,
 '882': 0.0007199841260368861,
 '129': 0.0007199472281642935,
 '1611': 0.0007197068191621957,
 '1292': 0.0007196025071715446,
 '1324': 0.0007196025071715446,
 '379': 0.0007194954547063605,
 '705': 0.0007191545466139873,
 '1848': 0.0007185344597857925,
 '1793': 0.0007172109023435037,
 '1672': 0.0007171830251227974,
 '1953': 0.000714135326927143,
 '1395': 0.0007137756046569687,
 '1396': 0.0007137756046569687,
 '1365': 0.0007136704008443832,
 '1938': 0.0007131310980432966,
 '822': 0.0007107278335433158,
 '49': 0.0007101822397916068,
 '1500': 0.0007098399776140917,
 '1579': 0.0007086955001958241,
 '1581': 0.0007086955001958241,
 '1587': 0.0007086955001958241,
 '1622': 0.0007086955001958241,
 '1682': 0.0007086955001958241,
 '1715': 0.0007086955001958241,
 '1716': 0.0007086955001958241,
 '1748': 0.0007086955001958241,
 '931': 0.0007085767339159956,
 '932': 0.0007085767339159956,
 '1950': 0.0007085767339159956,
 '1088': 0.0007081681696655677,
 '1596': 0.0007073719427535351,
 '1598': 0.0007073719427535351,
 '1698': 0.0007073719427535351,
 '1451': 0.000706586177640599,
 '1452': 0.000706586177640599,
 '1760': 0.0007051816729189329,
 '1233': 0.0007046075257369571,
 '1785': 0.0007042693408459282,
 '1808': 0.0007042693408459282,
 '1837': 0.0007042693408459282,
 '704': 0.0007029791341170362,
 '1812': 0.0007029457834036392,
 '1891': 0.0007021310631440667,
 '1892': 0.0007021310631440667,
 '302': 0.0006999302583432065,
 '1508': 0.0006980546516415585,
 '1994': 0.0006967030503393055,
 '840': 0.0006957008945928209,
 '2014': 0.0006956351724184201,
 '575': 0.0006954377693201684,
 '1216': 0.000695139082282062,
 '1355': 0.0006949988428694697,
 '1174': 0.000694004429676162,
 '370': 0.0006929642104305338,
 '1835': 0.000692345954009147,
 '1836': 0.000692345954009147,
 '1872': 0.0006911081177643718,
 '811': 0.0006907823998352798,
 '1805': 0.000688682528665338,
 '952': 0.0006884688663547543,
 '601': 0.000687987118974508,
 '1899': 0.0006878557680305519,
 '1919': 0.0006878557680305519,
 '1921': 0.0006878557680305519,
 '805': 0.0006850041477565607,
 '1878': 0.0006840349893252819,
 '1075': 0.0006833582861129442,
 '1861': 0.0006827148722779252,
 '1967': 0.0006822539292662183,
 '1400': 0.0006822330609475134,
 '1111': 0.0006816038857922971,
 '2002': 0.0006810329827640666,
 '1430': 0.0006778046313429099,
 '802': 0.00067756160711036,
 '803': 0.00067756160711036,
 '1700': 0.0006770255720064172,
 '1842': 0.0006763436414481736,
 '809': 0.0006741059138146404,
 '1827': 0.0006734552100783496,
 '1360': 0.0006729487582107889,
 '1159': 0.0006717875497588714,
 '1745': 0.0006683146674913809,
 '1734': 0.0006679453118329212,
 '1744': 0.0006679453118329212,
 '476': 0.0006676984632189992,
 '477': 0.0006676984632189992,
 '380': 0.0006666344808146388,
 '1161': 0.0006637480360290189,
 '1766': 0.0006628541923933264,
 '1578': 0.0006626056140238695,
 '765': 0.0006616978249867744,
 '768': 0.0006616978249867744,
 '763': 0.000660758280501562,
 '1982': 0.0006581784420135524,
 '1757': 0.000655730322268242,
 '1310': 0.0006554130802727301,
 '70': 0.0006542499080669489,
 '71': 0.0006542499080669489,
 '801': 0.0006535376475172448,
 '1969': 0.0006532968737618596,
 '1809': 0.0006530694472219203,
 '576': 0.0006503162244508438,
 '1296': 0.0006495448520426417,
 '1673': 0.0006482828106990705,
 '422': 0.0006477868456696712,
 '1930': 0.0006474180276491773,
 '554': 0.000646920104464614,
 '787': 0.0006458732853610153,
 '790': 0.0006458732853610153,
 '703': 0.0006458019621176784,
 '250': 0.0006453194221522903,
 '1758': 0.0006446968609090111,
 '1357': 0.000644616557363935,
 '821': 0.0006432787945702698,
 '234': 0.0006414305295401577,
 '240': 0.000639885874690151,
 '241': 0.000639885874690151,
 '274': 0.000639885874690151,
 '83': 0.0006395736147462159,
 '3': 0.0006390701836696498,
 '36': 0.0006390701836696498,
 '62': 0.0006390701836696498,
 '1023': 0.0006382770453561739,
 '64': 0.000636909594014112,
 '111': 0.0006358661071438206,
 '733': 0.0006349863530080253,
 '1934': 0.0006343896806397877,
 '1936': 0.0006343896806397877,
 '588': 0.0006338837758004146,
 '110': 0.0006325628013437718,
 '789': 0.0006324920733284571,
 '792': 0.0006324920733284571,
 '60': 0.0006314474586038253,
 '61': 0.0006314474586038253,
 '108': 0.0006312863494140504,
 '109': 0.0006312863494140504,
 '1262': 0.0006302091249481194,
 '880': 0.0006288183692142655,
 '168': 0.0006285313210300422,
 '170': 0.0006285313210300422,
 '278': 0.0006285313210300422,
 '1304': 0.000627229600335218,
 '450': 0.0006270270623990684,
 '486': 0.0006270270623990684,
 '1986': 0.0006269347482665096,
 '1081': 0.0006267911379928222,
 '795': 0.0006258941349379528,
 '1790': 0.0006252956152297429,
 '141': 0.0006237763670011318,
 '148': 0.0006237763670011318,
 '149': 0.0006237763670011318,
 '216': 0.0006237763670011318,
 '218': 0.0006237763670011318,
 '220': 0.0006237763670011318,
 '225': 0.0006237763670011318,
 '257': 0.0006237763670011318,
 '261': 0.0006237763670011318,
 '262': 0.0006237763670011318,
 '266': 0.0006237763670011318,
 '270': 0.0006237763670011318,
 '271': 0.0006237763670011318,
 '289': 0.0006237763670011318,
 '208': 0.0006234900155577195,
 '761': 0.0006223780553175353,
 '337': 0.000622272108370158,
 '344': 0.000622272108370158,
 '371': 0.000622272108370158,
 '373': 0.000622272108370158,
 '417': 0.000622272108370158,
 '447': 0.000622272108370158,
 '526': 0.000622272108370158,
 '527': 0.000622272108370158,
 '543': 0.000622272108370158,
 '544': 0.000622272108370158,
 '545': 0.000622272108370158,
 '558': 0.000622272108370158,
 '578': 0.000622272108370158,
 '590': 0.000622272108370158,
 '626': 0.000622272108370158,
 '1912': 0.0006216298074065587,
 '1156': 0.0006208338902181071,
 '1813': 0.000620439622426354,
 '1815': 0.000620439622426354,
 '1821': 0.000620439622426354,
 '649': 0.0006197326922299838,
 '650': 0.0006197326922299838,
 '665': 0.0006197326922299838,
 '864': 0.0006192769997376648,
 '928': 0.000618757819434168,
 '1334': 0.0006170739537940646,
 '726': 0.0006169897908010803,
 '778': 0.0006169897908010803,
 '1941': 0.0006164478423120978,
 '496': 0.0006163372123539115,
 '497': 0.0006163372123539115,
 '1165': 0.0006143455095491745,
 '794': 0.0006134686541309679,
 '1428': 0.000611920387941111,
 '548': 0.0006111249358608406,
 '158': 0.0006110155936726417,
 '1307': 0.0006104040083763075,
 '721': 0.000610207573429369,
 '282': 0.000609380163075697,
 '1047': 0.0006091873441682786,
 '1666': 0.0006075809218351843,
 '933': 0.0006069163660245105,
 '978': 0.0006069163660245105,
 '979': 0.0006069163660245105,
 '1654': 0.0006065230513665309,
 '1632': 0.0006064309447543067,
 '1644': 0.0006064309447543067,
 '1645': 0.0006064309447543067,
 '296': 0.0006063162456677189,
 '313': 0.0006063162456677189,
 '357': 0.00060587524747403,
 '1468': 0.0006058151163461099,
 '613': 0.0006051006856344894,
 '1659': 0.0006046706389278424,
 '1665': 0.0006046706389278424,
 '1108': 0.0006044833917838593,
 '1225': 0.0006033248263739465,
 '1784': 0.0006024831114514234,
 '946': 0.0006021614119956001,
 '1424': 0.0006013894268242401,
 '1735': 0.0006007052584248568,
 '1743': 0.0006007052584248568,
 '645': 0.0006006428364084798,
 '646': 0.0006006428364084798,
 '1030': 0.0005997284377549489,
 '1044': 0.0005997284377549489,
 '1051': 0.0005997284377549489,
 '1062': 0.0005997284377549489,
 '1064': 0.0005997284377549489,
 '1104': 0.0005997284377549489,
 '1125': 0.0005997284377549489,
 '1133': 0.0005997284377549489,
 '1505': 0.0005993327363887723,
 '251': 0.0005988917432657634,
 '1358': 0.000598784973811981,
 '1460': 0.0005986207800588362,
 '1195': 0.0005985698723450362,
 '1212': 0.0005985698723450362,
 '1235': 0.0005985698723450362,
 '1255': 0.0005985698723450362,
 '1291': 0.0005985698723450362,
 '1294': 0.0005985698723450362,
 '1327': 0.0005985698723450362,
 '1328': 0.0005985698723450362,
 '1339': 0.0005985698723450362,
 '1421': 0.0005975931040404585,
 '1474': 0.0005975931040404585,
 '1547': 0.0005954253866454478,
 '1548': 0.0005954253866454478,
 '989': 0.0005947781143719222,
 '1295': 0.0005940068836142984,
 '1369': 0.0005939613234601638,
 '0': 0.0005937963957846055,
 '654': 0.0005931309459316138,
 '252': 0.0005928214473765517,
 '1729': 0.0005927659711976588,
 '734': 0.0005918060087543066,
 '1515': 0.0005916936725932807,
 '1566': 0.0005916936725932807,
 '1567': 0.0005916936725932807,
 '1727': 0.0005914424137553699,
 '1733': 0.0005914424137553699,
 '1736': 0.0005914424137553699,
 '1740': 0.0005914424137553699,
 '1742': 0.0005914424137553699,
 '1060': 0.0005910068036765447,
 '1132': 0.0005910068036765447,
 '1135': 0.0005910068036765447,
 '1143': 0.0005910068036765447,
 '1309': 0.0005907838054061827,
 '1693': 0.0005907535561910953,
 '1696': 0.0005907535561910953,
 '1576': 0.0005905847859117955,
 '1591': 0.0005904638254303522,
 '369': 0.0005898796676237945,
 '655': 0.0005896476066168831,
 '1539': 0.000589533082937743,
 '597': 0.0005895262454213456,
 '1650': 0.000589394628633926,
 '1651': 0.000589394628633926,
 '1655': 0.000589394628633926,

### Coeficiente de agrupamiento

In [37]:
dict(sorted(nx.clustering(G).items(), key=lambda item: item[1], reverse=True))

{'1979': 0.6625,
 '35': 0.6621848739495798,
 '1746': 0.6559006211180124,
 '1690': 0.6368159203980099,
 '93': 0.6364692218350755,
 '96': 0.6276276276276276,
 '1535': 0.6159147869674185,
 '1664': 0.6159147869674185,
 '1915': 0.6121593291404612,
 '1393': 0.6085904416212946,
 '1479': 0.6085904416212946,
 '95': 0.6079365079365079,
 '94': 0.6060606060606061,
 '1131': 0.6049165935030729,
 '1283': 0.6049165935030729,
 '608': 0.6042105263157894,
 '694': 0.6042105263157894,
 '1472': 0.5938047925189948,
 '249': 0.5909090909090909,
 '1477': 0.5865853658536585,
 '693': 0.5814889336016097,
 '1620': 0.5806451612903226,
 '1379': 0.5790816326530612,
 '1619': 0.5750999428897773,
 '104': 0.5745762711864407,
 '1924': 0.5711111111111111,
 '1279': 0.56579476861167,
 '255': 0.5648567119155354,
 '629': 0.5622119815668203,
 '1869': 0.5615171137835338,
 '1897': 0.5563025210084034,
 '1629': 0.5518619819061645,
 '1862': 0.5507936507936508,
 '1185': 0.5482866043613707,
 '1184': 0.5423687423687423,
 '1606': 0.5400350672121567,
 '843': 0.5363115145723841,
 '309': 0.5360576923076923,
 '670': 0.5360576923076923,
 '480': 0.5329824561403509,
 '2': 0.5317460317460317,
 '1864': 0.5270655270655271,
 '1533': 0.5209836941994119,
 '126': 0.5198889916743756,
 '128': 0.5198889916743756,
 '797': 0.5198889916743756,
 '695': 0.519795062878435,
 '1980': 0.5128851540616246,
 '1288': 0.5111721611721611,
 '317': 0.509657594381036,
 '136': 0.5076923076923077,
 '307': 0.5034385469934756,
 '835': 0.5024242424242424,
 '174': 0.5013225180744136,
 '1722': 0.5007112375533428,
 '27': 0.5003912363067292,
 '46': 0.4985014985014985,
 '28': 0.4982148653034729,
 '1720': 0.4975609756097561,
 '816': 0.4972232506479082,
 '339': 0.4965626652564781,
 '1631': 0.4955555555555556,
 '935': 0.4954954954954955,
 '1517': 0.4950166112956811,
 '1257': 0.4939271255060729,
 '830': 0.49235547061634016,
 '1426': 0.49169435215946844,
 '1512': 0.4893713251922207,
 '19': 0.4883720930232558,
 '1735': 0.4862699237699238,
 '1743': 0.4862699237699238,
 '388': 0.4855769230769231,
 '1346': 0.4847782319565615,
 '1914': 0.4847508591065292,
 '1755': 0.4847141720650074,
 '466': 0.48294970161977835,
 '1727': 0.48241164995690244,
 '1733': 0.48241164995690244,
 '1736': 0.48241164995690244,
 '1740': 0.48241164995690244,
 '1742': 0.48241164995690244,
 '1729': 0.481555766364006,
 '180': 0.4809725158562368,
 '754': 0.4809725158562368,
 '850': 0.4809725158562368,
 '1139': 0.48088531187122735,
 '1553': 0.48088531187122735,
 '1867': 0.48072199914233366,
 '1428': 0.4806894536955887,
 '1726': 0.4802862069344228,
 '1728': 0.4802862069344228,
 '1732': 0.4802862069344228,
 '1741': 0.4802862069344228,
 '1199': 0.4789021657953697,
 '849': 0.4785165083672546,
 '124': 0.47838745800671895,
 '138': 0.47838745800671895,
 '745': 0.47838745800671895,
 '254': 0.4781884781884782,
 '1552': 0.47767857142857145,
 '1839': 0.47632850241545893,
 '1307': 0.47618641901678455,
 '1427': 0.4758281888531432,
 '1306': 0.4757207417796478,
 '191': 0.47560975609756095,
 '2027': 0.47478853845649466,
 '973': 0.47463002114164904,
 '1147': 0.4736263736263736,
 '1975': 0.47297297297297297,
 '183': 0.47293447293447294,
 '1752': 0.472572598740823,
 '1754': 0.472572598740823,
 '1367': 0.4725409836065574,
 '246': 0.47244805781391147,
 '92': 0.4724170172978027,
 '1100': 0.47147147147147145,
 '114': 0.4708333333333333,
 '135': 0.4701951349906442,
 '1586': 0.4701298701298701,
 '1990': 0.46993599934776403,
 '1997': 0.46993599934776403,
 '2024': 0.46993599934776403,
 '1071': 0.4695655155858853,
 '1187': 0.4695655155858853,
 '1102': 0.4694560669456067,
 '1734': 0.46897393631328843,
 '1744': 0.46897393631328843,
 '131': 0.46888320545609546,
 '551': 0.46871529063309886,
 '1227': 0.4685289316161799,
 '190': 0.46846846846846846,
 '1757': 0.4680510033925594,
 '1974': 0.4672364672364672,
 '1156': 0.4668612609046983,
 '167': 0.46681749622926094,
 '886': 0.4666666666666667,
 '944': 0.4666666666666667,
 '703': 0.4662292350153622,
 '1138': 0.4661224489795918,
 '1556': 0.4661224489795918,
 '1256': 0.46581972171808833,
 '1555': 0.46581972171808833,
 '1505': 0.46568954030646237,
 '592': 0.4655113829425756,
 '1261': 0.46544025914333864,
 '1226': 0.4654255319148936,
 '996': 0.4651319862666742,
 '1103': 0.4651319862666742,
 '1193': 0.4651319862666742,
 '1213': 0.4651319862666742,
 '433': 0.46511627906976744,
 '851': 0.4649257552483359,
 '983': 0.4646176911544228,
 '436': 0.4645390070921986,
 '507': 0.4645390070921986,
 '1172': 0.46430084890571816,
 '735': 0.46396626194605994,
 '1557': 0.46365248226950356,
 '982': 0.46364221364221364,
 '1157': 0.46348203338677735,
 '681': 0.4626865671641791,
 '1430': 0.4626099068512231,
 '1260': 0.46187915216703573,
 '223': 0.461624649859944,
 '1758': 0.46154305728773815,
 '408': 0.46115288220551376,
 '75': 0.4610500610500611,
 '1258': 0.4608843537414966,
 '1035': 0.46078431372549017,
 '202': 0.4605493863237873,
 '214': 0.4605493863237873,
 '350': 0.4605493863237873,
 '336': 0.46,
 '1554': 0.4596736596736597,
 '386': 0.45964912280701753,
 '821': 0.4592421895659401,
 '276': 0.4586894586894587,
 '338': 0.45801271328203413,
 '343': 0.45801271328203413,
 '346': 0.45801271328203413,
 '348': 0.45801271328203413,
 '487': 0.45801271328203413,
 '489': 0.45801271328203413,
 '550': 0.45801271328203413,
 '787': 0.4578216604441246,
 '790': 0.4578216604441246,
 '789': 0.4575470572798626,
 '792': 0.4575470572798626,
 '1165': 0.4574069848995699,
 '836': 0.45734265734265733,
 '139': 0.45714285714285713,
 '852': 0.45701357466063347,
 '1723': 0.4568764568764569,
 '21': 0.45663265306122447,
 '201': 0.45663265306122447,
 '213': 0.45663265306122447,
 '353': 0.45663265306122447,
 '332': 0.4566145092460882,
 '192': 0.45614035087719296,
 '1174': 0.4560695118834654,
 '815': 0.4559139784946237,
 '1778': 0.45590900327742434,
 '134': 0.45574912891986064,
 '184': 0.45574912891986064,
 '219': 0.45574912891986064,
 '260': 0.45574912891986064,
 '265': 0.45574912891986064,
 '290': 0.45574912891986064,
 '1984': 0.4548616600790514,
 '334': 0.4546938775510204,
 '490': 0.4546938775510204,
 '1267': 0.45459770114942527,
 '744': 0.4543816543816544,
 '1173': 0.4535573641375689,
 '1175': 0.4535573641375689,
 '1893': 0.4535454096885612,
 '1245': 0.45215100965759436,
 '1681': 0.451413085559427,
 '1036': 0.45134218201297543,
 '1295': 0.4507190491312435,
 '2026': 0.45051031097542726,
 '1159': 0.4502576788291074,
 '1251': 0.4499225468724961,
 '1106': 0.4497457686146131,
 '1268': 0.4493014444707554,
 '305': 0.44927211646136617,
 '1656': 0.4488341968911917,
 '181': 0.44872269529803777,
 '1995': 0.4482373678025852,
 '51': 0.44799658994032393,
 '667': 0.44799658994032393,
 '1695': 0.447778926756287,
 '434': 0.44743589743589746,
 '437': 0.44743589743589746,
 '470': 0.44743589743589746,
 '1780': 0.44731447314473144,
 '1970': 0.4470416987755801,
 '1308': 0.4469038208168643,
 '1073': 0.44637328054413483,
 '1831': 0.4461538461538462,
 '947': 0.4461277420918677,
 '1989': 0.4461277420918677,
 '1045': 0.4460852176588217,
 '1061': 0.4460852176588217,
 '1215': 0.4460852176588217,
 '570': 0.44565826330532216,
 '557': 0.44549713690786047,
 '1519': 0.44530154277699857,
 '352': 0.44526705446853515,
 '1981': 0.44507141597601835,
 '1697': 0.44502636843062376,
 '673': 0.44463276836158194,
 '26': 0.44452070464424615,
 '42': 0.44452070464424615,
 '1417': 0.44439137011384444,
 '1630': 0.44430217669654287,
 '822': 0.4440925566580017,
 '1252': 0.44393514981750276,
 '321': 0.44383706577323223,
 '1394': 0.44366744366744365,
 '704': 0.4435598361424685,
 '1237': 0.44350437835779855,
 '30': 0.44258760107816714,
 '1745': 0.4423838750174362,
 '865': 0.44238228449187805,
 '1211': 0.4421161825726141,
 '1072': 0.4420288351830723,
 '247': 0.44202020202020204,
 '248': 0.44202020202020204,
 '1510': 0.4419642857142857,
 '588': 0.4416426111919587,
 '834': 0.4415653093601269,
 '1985': 0.44126984126984126,
 '753': 0.4412191582002903,
 '1475': 0.4411785739826933,
 '1968': 0.44068119607775197,
 '1661': 0.440467696054647,
 '57': 0.44013401516487394,
 '1668': 0.44005369866786,
 '950': 0.4400231268918138,
 '1562': 0.43974358974358974,
 '788': 0.4396880061470086,
 '791': 0.4396880061470086,
 '1065': 0.43951582587775356,
 '1730': 0.43938223938223936,
 '1568': 0.4393162393162393,
 '1643': 0.43891891891891893,
 '222': 0.43883792048929665,
 '945': 0.43881340109947103,
 '1337': 0.4383750324086077,
 '1933': 0.4382499961783634,
 '322': 0.4379884471627591,
 '984': 0.43767337807606266,
 '892': 0.43708357129259473,
 '1136': 0.43677375256322626,
 '1444': 0.4365841407223516,
 '1504': 0.4365841407223516,
 '2018': 0.4361434262948207,
 '435': 0.43609022556390975,
 '2028': 0.43603782976605276,
 '728': 0.4358318923389219,
 '794': 0.4356200415765135,
 '43': 0.43548387096774194,
 '887': 0.4354152823920266,
 '663': 0.4353996976052285,
 '1951': 0.43538461538461537,
 '1988': 0.43538461538461537,
 '385': 0.43525011687704535,
 '1635': 0.43514417231196806,
 '1686': 0.43514417231196806,
 '1046': 0.43482257767972055,
 '11': 0.43356643356643354,
 '396': 0.43356643356643354,
 '2019': 0.43352487919550736,
 '680': 0.4331065759637188,
 '715': 0.4331065759637188,
 '1476': 0.4325719960278054,
 '132': 0.43245179781136006,
 '488': 0.43245179781136006,
 '555': 0.43245179781136006,
 '1783': 0.4324088037942867,
 '1838': 0.4324088037942867,
 '1676': 0.43240434577231934,
 '449': 0.4323986194995686,
 '959': 0.43236409608091025,
 '112': 0.43217189314750293,
 '1649': 0.43202911737943583,
 '1671': 0.4319203923404082,
 '995': 0.43190394511149227,
 '1006': 0.43190394511149227,
 '1436': 0.43166989948862633,
 '2017': 0.43142037302725966,
 '1599': 0.43093196112064036,
 '1391': 0.43047049603808085,
 '419': 0.43023516237402015,
 '137': 0.4301572617946346,
 '383': 0.43013923013923017,
 '864': 0.43011923019838716,
 '1420': 0.4300537666408745,
 '1520': 0.4298534798534799,
 '1524': 0.4298534798534799,
 '1274': 0.429732396818947,
 '997': 0.42967289719626167,
 '1093': 0.42967289719626167,
 '1196': 0.42967289719626167,
 '1236': 0.42967289719626167,
 '1239': 0.42967289719626167,
 '1329': 0.42967289719626167,
 '200': 0.4292058516196447,
 '1669': 0.4291167566144531,
 '156': 0.42901001437586805,
 '736': 0.4289702899415344,
 '1518': 0.42894027521634276,
 '142': 0.42892896577107104,
 '644': 0.4288824383164006,
 '1731': 0.428820531163373,
 '1863': 0.4288135593220339,
 '1865': 0.4288135593220339,
 '284': 0.4287422285987566,
 '793': 0.4287304694997889,
 '1419': 0.42833989470437234,
 '1271': 0.42832779623477296,
 '817': 0.4281880635465865,
 '1188': 0.4281767955801105,
 '1738': 0.4281112039136141,
 '1992': 0.4280387770320656,
 '807': 0.4277706598334401,
 '845': 0.4273825503355705,
 '938': 0.42735499794323323,
 '1221': 0.42707414240260955,
 '953': 0.4270024206076809,
 '1739': 0.42690311418685123,
 '1529': 0.4268637252771137,
 '517': 0.42671660424469415,
 '795': 0.4263330989955799,
 '934': 0.42630814509039483,
 '1207': 0.4262368815592204,
 '394': 0.42621825669183255,
 '961': 0.4262061804126685,
 '505': 0.4260666277030976,
 '563': 0.4260666277030976,
 '1218': 0.4260666277030976,
 '1219': 0.4260666277030976,
 '1928': 0.4260666277030976,
 '2010': 0.4260666277030976,
 '2022': 0.4260666277030976,
 '2023': 0.4260666277030976,
 '633': 0.4260102447353443,
 '1530': 0.4258128078817734,
 '1569': 0.4258128078817734,
 '1737': 0.42574626865671644,
 '530': 0.4256254980079681,
 '971': 0.4255952380952381,
 '975': 0.4255952380952381,
 '796': 0.42538852977582176,
 '1181': 0.42528735632183906,
 '412': 0.4246823956442831,
 '485': 0.42466640756574686,
 '133': 0.4243502677288755,
 '258': 0.4243502677288755,
 '345': 0.4243502677288755,
 '784': 0.4242478543808356,
 '263': 0.4241210502892746,
 '648': 0.42396039603960395,
 '179': 0.4236326109391125,
 '277': 0.4236326109391125,
 '610': 0.4236326109391125,
 '1107': 0.4230566534914361,
 '1932': 0.4228694199092862,
 '1578': 0.42255355903884007,
 '1336': 0.42223037417461484,
 '171': 0.4218840078404243,
 '1602': 0.4218378113114955,
 '1210': 0.4215857202158572,
 '166': 0.4214689265536723,
 '1972': 0.4214105419450631,
 '827': 0.42104766399244925,
 '841': 0.42104766399244925,
 '12': 0.4207282913165266,
 '333': 0.4207282913165266,
 '446': 0.4207282913165266,
 '252': 0.42071597210783507,
 '440': 0.4205940594059406,
 '1969': 0.42043845693518017,
 '1856': 0.42042042042042044,
 '106': 0.4201016374929418,
 '742': 0.41998361998362,
 '33': 0.4197901049475262,
 '1020': 0.4191368350618936,
 '1204': 0.4188765326489877,
 '999': 0.4188359422295252,
 '367': 0.4186708860759494,
 '632': 0.4185644051130777,
 '1811': 0.41851826054653946,
 '456': 0.41835748792270533,
 '193': 0.41802782819116757,
 '272': 0.41785714285714287,
 '1597': 0.41775444457701943,
 '1853': 0.41763302561974897,
 '306': 0.41714285714285715,
 '442': 0.41711229946524064,
 '668': 0.41711229946524064,
 '451': 0.41646489104116224,
 '347': 0.41645945295580333,
 '819': 0.4162248995983936,
 '968': 0.41613925617788344,
 '1809': 0.4160434178304322,
 '808': 0.4160361377752682,
 '820': 0.4160088213918753,
 '1522': 0.41600353669319184,
 '897': 0.41599427255664556,
 '1289': 0.41598569969356486,
 '1323': 0.4154334038054968,
 '528': 0.4152218630620041,
 '279': 0.4147631502470212,
 '291': 0.4147133905778603,
 '1309': 0.4143139236935518,
 '1787': 0.41427066084600334,
 '413': 0.4140666314119513,
 '414': 0.41351981351981354,
 '1249': 0.4135073179333451,
 '194': 0.41338760741745817,
 '195': 0.41338760741745817,
 '251': 0.41336358500537607,
 '150': 0.41305361305361304,
 '151': 0.41305361305361304,
 '152': 0.41305361305361304,
 '1849': 0.41303993922292165,
 '1710': 0.41296999742467166,
 '1387': 0.41294284364666983,
 '215': 0.41292468519838443,
 '977': 0.41251885369532426,
 '1326': 0.41251885369532426,
 '196': 0.41233766233766234,
 '72': 0.41231671554252197,
 '308': 0.41231671554252197,
 '949': 0.412139649427785,
 '1075': 0.41212290428516346,
 '2007': 0.4119513484928609,
 '899': 0.41192170818505336,
 '1585': 0.41112618724559025,
 '1621': 0.41112618724559025,
 '1229': 0.41078583294942134,
 '467': 0.4106788710907704,
 '926': 0.41055113468906573,
 '1913': 0.41038208168642953,
 '34': 0.41037141374453256,
 '250': 0.4102326932485323,
 '1074': 0.410163925743492,
 '713': 0.4100085910652921,
 '1099': 0.40965732087227413,
 '340': 0.40934065934065933,
 '2009': 0.40914158305462656,
 '952': 0.4090795922111277,
 '969': 0.40901272789817683,
 '569': 0.40874914559125086,
 '349': 0.4085441058182143,
 '556': 0.4085441058182143,
 '617': 0.4085441058182143,
 '1371': 0.4084507042253521,
 '1380': 0.4084507042253521,
 '568': 0.4082882882882883,
 '1763': 0.407937677650279,
 '837': 0.4079192546583851,
 '1063': 0.40758075382051556,
 '1238': 0.40758075382051556,
 '86': 0.40727848101265823,
 '115': 0.4072618886329766,
 '1996': 0.40713384975680056,
 '614': 0.4070693901202376,
 '283': 0.4070393374741201,
 '1429': 0.4069926509379562,
 '640': 0.40698869475847893,
 '1418': 0.4069264069264069,
 '524': 0.4067421939762365,
 '623': 0.405864311127469,
 '1638': 0.4056603773584906,
 '1978': 0.40562057161054055,
 '1375': 0.40555555555555556,
 '1670': 0.40555555555555556,
 '786': 0.4054667714610078,
 '1694': 0.40533219275734245,
 '672': 0.4052464947987336,
 '943': 0.4052248514468549,
 '1721': 0.404921165790731,
 '1531': 0.4048922964585615,
 '1167': 0.4047883260278533,
 '1750': 0.40474349059035836,
 '407': 0.40466200466200464,
 '1971': 0.4045864933188877,
 '1840': 0.40445907526559927,
 '1775': 0.4043020193151888,
 '1511': 0.4042446941323346,
 '1216': 0.40422096792942663,
 '712': 0.4041274817136886,
 '431': 0.4039938556067588,
 '469': 0.4039938556067588,
 '432': 0.40375586854460094,
 '438': 0.40375586854460094,
 '468': 0.40375586854460094,
 '506': 0.40375586854460094,
 '508': 0.40375586854460094,
 '664': 0.4037344398340249,
 '1660': 0.4036559931296773,
 '1747': 0.40283570640970323,
 '78': 0.4028192752623918,
 '79': 0.4026192241166296,
 '80': 0.4026192241166296,
 '1440': 0.4024540220247079,
 '1762': 0.4022591991341991,
 '1137': 0.40223964165733483,
 '1485': 0.40223964165733483,
 '1486': 0.40223964165733483,
 '1516': 0.40223964165733483,
 '1577': 0.40223964165733483,
 '710': 0.4018895348837209,
 '911': 0.4018649805198953,
 '894': 0.4018264840182648,
 '1560': 0.4017094017094017,
 '1764': 0.40127366391706965,
 '1616': 0.4011835526987042,
 '679': 0.40116381590548406,
 '758': 0.40108100982136974,
 '404': 0.40100250626566414,
 '47': 0.4009410878976096,
 '18': 0.4006578947368421,
 '20': 0.4006578947368421,
 '68': 0.4006578947368421,
 '203': 0.4006578947368421,
 '212': 0.4006578947368421,
 '351': 0.4006578947368421,
 '566': 0.4006578947368421,
 '603': 0.4006578947368421,
 '604': 0.4006578947368421,
 '169': 0.40054726368159205,
 '936': 0.400447928331467,
 '1457': 0.4002385840315153,
 '15': 0.4,
 '32': 0.4,
 '1373': 0.4,
 '1458': 0.3999718230487461,
 '1459': 0.3999718230487461,
 '1478': 0.3999718230487461,
 '951': 0.3999623564840956,
 '1945': 0.39964633068081346,
 '1514': 0.3996293128029655,
 '1534': 0.3996293128029655,
 '1607': 0.3996293128029655,
 '1623': 0.3996293128029655,
 '1688': 0.3996293128029655,
 '1925': 0.39943255885284873,
 '1208': 0.3993038635572572,
 '805': 0.3991602547361231,
 '509': 0.3990532487504806,
 '1253': 0.39892183288409705,
 '960': 0.3988048576752554,
 '1445': 0.39859909353110834,
 '256': 0.3985307621671258,
 '264': 0.3985307621671258,
 '273': 0.3985307621671258,
 '457': 0.3985307621671258,
 '2004': 0.39832285115303984,
 '913': 0.39823168235775686,
 '1834': 0.39816933638443935,
 '409': 0.3979591836734694,
 '1636': 0.3979540499748449,
 '1105': 0.39766081871345027,
 '2020': 0.3975270071065543,
 '1220': 0.3975230566534914,
 '525': 0.3975151152747326,
 '1000': 0.39750832971171957,
 '1160': 0.3974818191685662,
 '1934': 0.397464566274575,
 '1936': 0.397464566274575,
 '1194': 0.3974625975166327,
 '1209': 0.3974625975166327,
 '1214': 0.3974625975166327,
 '1624': 0.39734671125975474,
 '1473': 0.39728601733997415,
 '14': 0.3971658006613132,
 '269': 0.397108843537415,
 '341': 0.396925551881312,
 '1186': 0.39685068204705665,
 '81': 0.3965461062235256,
 '1422': 0.3964314126605296,
 '1634': 0.3964037294657392,
 '1364': 0.3963646303129698,
 '1095': 0.39631398173745497,
 '1130': 0.39631398173745497,
 '1121': 0.39559651817716335,
 '1464': 0.3955304128290243,
 '1491': 0.3955304128290243,
 '382': 0.3954699612403101,
 '927': 0.3950819672131147,
 '727': 0.39503081664098616,
 '1197': 0.3948111305282968,
 '1205': 0.3948111305282968,
 '1217': 0.3948111305282968,
 '1248': 0.3948111305282968,
 '1263': 0.3948111305282968,
 '1264': 0.3948111305282968,
 '66': 0.3945846204880476,
 '1492': 0.3940292384575222,
 '1523': 0.3939393939393939,
 '523': 0.39384615384615385,
 '1027': 0.39383944108251306,
 '1162': 0.39351840753082573,
 '1572': 0.39332365747460085,
 '498': 0.3928884986830553,
 '323': 0.3927827897293546,
 '1242': 0.3927729772191673,
 '1689': 0.39268461007591443,
 '1691': 0.39268461007591443,
 '1368': 0.39203328889427547,
 '705': 0.3919867149758454,
 '1012': 0.39193409075808916,
 '1013': 0.39193409075808916,
 '1034': 0.39193409075808916,
 '1057': 0.3918767507002801,
 '1': 0.3915689199267747,
 '379': 0.39103119584055457,
 '1166': 0.39089234008949725,
 '1169': 0.39089234008949725,
 '1858': 0.3902439024390244,
 '403': 0.39019963702359345,
 '1123': 0.3899468843114393,
 '1122': 0.38982640645970384,
 '288': 0.38973362930077693,
 '1526': 0.38919553728714035,
 '405': 0.38917306052855927,
 '759': 0.3890441767068273,
 '1402': 0.3887512291052114,
 '707': 0.3886842105263158,
 '259': 0.38836231247253783,
 '896': 0.38834611938014996,
 '172': 0.3882317059887153,
 '1168': 0.38797279560911585,
 '1170': 0.38797279560911585,
 '1705': 0.3878279770222015,
 '1471': 0.3876193036698481,
 '1991': 0.38724012674858954,
 '2015': 0.38724012674858954,
 '161': 0.3872115217768523,
 '1171': 0.3871710354209177,
 '406': 0.38666666666666666,
 '1976': 0.38666666666666666,
 '1609': 0.3861877494360576,
 '7': 0.3857777777777778,
 '165': 0.3857777777777778,
 '237': 0.3857777777777778,
 '1484': 0.38546847694582603,
 '1563': 0.385369532428356,
 '607': 0.38429081467056153,
 '1525': 0.38427518427518426,
 '1241': 0.38416143156291643,
 '1850': 0.3839958158995816,

### Coeficiente de agrupamiento medio

In [38]:
nx.average_clustering(G)

0.344343888741553

## 3. Obtención de los looks

### Triángulos

In [39]:
num_triangulos = nx.triangles(G)
sum(num_triangulos.values()) // 3

15628397

In [40]:
G_igraph = Graph.from_networkx(G)
triangulos = G_igraph.cliques(min=3, max=3)

### Filtrar los triangulos para que cumplan las reglas 9, 10 y 11.

**Regla 9** : al generar tríos (looks), al menos una de las prendas conectadas debe tener basic = True.

In [41]:
basic_nodes = set(df_grafo.index[df_grafo["basic"]])

triangulos_filtrados_basic = [
    t for t in triangulos
    if any(n in basic_nodes for n in t)
]

**Regla 10 y 11**: los looks tienen que tener siempre una prenda de nivel 1 o 2. Si el look contiene una prenda primer nivel, tiene que tener dos de cuarto nivel. Si el look contiene una prenda de segundo nivel, tiene que tener uno de tercer y otro de cuarto nivel.

In [42]:
nivel_dict = df_grafo["nivel"].to_dict()
triangulos_filtrados = filtrar_triangulos(triangulos_filtrados_basic, nivel_dict)

In [43]:
len(triangulos_filtrados)

730236

### Función para obtener los looks

Se han generado una cantidad de 15 looks

In [68]:
def generar_looks_10(df_expandido, triangulos_filtrados):
    import pandas as pd

    # --- 0) Formatos ---
    df = df_expandido.copy()

    # Si ya cambiaste el nombre afuera, esto asegura que la función lo encuentre
    if "index" not in df.columns:
        if "indice" in df.columns:
            df = df.rename(columns={'indice': 'index'})
        else:
            raise ValueError("df_expandido debe tener una columna 'index' o 'indice'.")

    df["index"] = df["index"].astype(int)
    df["hexadecimal"] = (
        df["hexadecimal"].astype(str).str.strip().str.lstrip("#").str.upper()
    )

    # --- 1) Acceso rápido ---
    row_by_node = df.set_index("index", drop=True)

    # --- 2) Detectores ---
    def _col(df_look, name):
        if name not in df_look.columns:
            return pd.Series([""] * len(df_look), index=df_look.index)
        return df_look[name]

    def tiene_vestido(df_look):
        cat = _col(df_look, "categoria_prenda").astype(str)
        sub = _col(df_look, "subcategoria_prenda").astype(str)
        return cat.str.lower().isin({"dress"}).any() or sub.str.contains("dress", case=False, na=False).any()

    def tiene_falda(df_look):
        sub = _col(df_look, "subcategoria_prenda").astype(str)
        return sub.str.contains("skirt", case=False, na=False).any()

    def tiene_pantalon(df_look):
        sub = _col(df_look, "subcategoria_prenda").astype(str)
        return sub.str.contains("pant|trouser|jean|cigarette", case=False, na=False).any()

    def tiene_accesorio(df_look):
        cat = _col(df_look, "categoria_prenda").astype(str)
        sub = _col(df_look, "subcategoria_prenda").astype(str)
        niv = _col(df_look, "nivel")
        try:
            niv_num = pd.to_numeric(niv, errors="coerce")
        except Exception:
            niv_num = pd.Series([None] * len(df_look), index=df_look.index)
        return (
            cat.str.lower().isin({"accessories"}).any()
            or sub.str.contains("bag|foulard|scarf|belt", case=False, na=False).any()
            or (niv_num == 4).any()
        )

    # --- 3) Análisis ---
    HEX_AZULES = {"00008B", "000080", "153668", "1E90FF", "0B3D91"}

    def analiza_look(nodes):
        # Al llegar aquí ya sabemos que los nodos existen gracias al check en 'pasada'
        df_look = row_by_node.loc[list(nodes)]
        colores = set(_col(df_look, "hexadecimal").unique())
        color_distinto = len(colores) > 1

        return {
            "df": df_look,
            "colores": colores,
            "color_distinto": color_distinto,
            "azul": len(colores & HEX_AZULES) > 0,
            "vestido": tiene_vestido(df_look),
            "falda": tiene_falda(df_look),
            "pantalon": tiene_pantalon(df_look),
            "accesorio": tiene_accesorio(df_look),
        }

    # --- 4) Lógica de Selección ---
    target = {"vestidos": 2, "faldas": 2, "pantalones": 3, "accesorios": 3}
    PRIORIDAD = ["vestidos", "faldas", "pantalones", "accesorios"]
    looks = {"vestidos": [], "faldas": [], "pantalones": [], "accesorios": []}
    numeros_usados = set()
    blue_usado = {"faldas": False, "pantalones": False, "accesorios": False}

    def total_actual(): return sum(len(v) for v in looks.values())
    def cupo_lleno(cat): return len(looks[cat]) >= target[cat]
    
    def cumple_cat(cat, info):
        return (
            (cat == "vestidos" and info["vestido"]) or
            (cat == "faldas" and info["falda"]) or
            (cat == "pantalones" and info["pantalon"]) or
            (cat == "accesorios" and info["accesorio"])
        )

    def puede_entrar(cat, info):
        if cupo_lleno(cat): return False
        if not cumple_cat(cat, info): return False
        if cat in blue_usado and info["azul"] and blue_usado[cat]: return False
        return True

    def add_to(cat, look, info):
        looks[cat].append(look)
        numeros_usados.update(look)
        if cat in blue_usado and info["azul"]:
            blue_usado[cat] = True

    def pasada(exigir_color_distinto=True):
        for look in triangulos_filtrados:
            if total_actual() >= 10: break
            
            # --- CORRECCIÓN AQUÍ: Validar que todos los nodos del triángulo están en el DF ---
            if not all(n in row_by_node.index for n in look):
                continue
            
            if any(n in numeros_usados for n in look):
                continue

            info = analiza_look(look)
            if exigir_color_distinto and not info["color_distinto"]:
                continue

            for cat in PRIORIDAD:
                if puede_entrar(cat, info):
                    add_to(cat, look, info)
                    break

    pasada(exigir_color_distinto=True)
    if total_actual() < 10:
        pasada(exigir_color_distinto=False)

    return looks, row_by_node

In [69]:
df_expandido = pd.read_csv("../Datos/Transformados/df_expandido.csv",sep=';')

In [70]:
df_expandido = df_expandido.rename(columns={'indice': 'index'})

In [72]:
looks, row_by_node = generar_looks_10(df_expandido, triangulos_filtrados)

print({k: len(v) for k, v in looks.items()}, "TOTAL =", sum(len(v) for v in looks.values()))

{'vestidos': 2, 'faldas': 2, 'pantalones': 3, 'accesorios': 3} TOTAL = 10

In [73]:
from IPython.display import display

def mostrar_look(look):
    cols = ["nombre_producto","categoria_prenda","subcategoria_prenda","nivel","hexadecimal","basic","weather","style","application"]
    cols_ok = [c for c in cols if c in row_by_node.columns]  # por si falta alguna
    return row_by_node.loc[list(look), cols_ok]

for cat, lista in looks.items():
    for i, lk in enumerate(lista, 1):
        print(f"\n--- {cat.upper()} {i} ---")
        display(mostrar_look(lk))

--- VESTIDOS 1 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
407,Elle Tshirt cotton,top,t-shirts,3,000000,False,warm_season,casual,freetime
1404,French Dress fifine,dress,with_pleat,1,87CEFA,False,warm_season,boho,freetime
1810,Filena Cardigan nais,top,cardigan,3,D3D3D3,False,warm_season,boho,work

--- VESTIDOS 2 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
405,Elle Tshirt cotton,top,t-shirts,3,87CEFA,False,warm_season,casual,freetime
1302,Elise Sweatshirt hoody,top,hoodies,3,000081,False,cold_season,casual,freetime
1434,Itsolid Dress hippie,dress,with_pleat,1,000000,False,warm_season,boho,freetime

--- FALDAS 1 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
855,Medos Tshirt slub,top,t-shirts,3,00008B,False,warm_season,casual,freetime
1117,Paniz Short regular,bottoms,shorts,2,FFFFFF,False,warm,classic,freetime
1316,Addi Skirt even,skirt,circle_skirt,2,ECE9D6,False,warm_season,boho,freetime

--- FALDAS 2 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
151,Closet Shirt maine,top,shirt,3,ECE9D6,False,warm_season,classic,freetime
166,Closet Dress michigan,dress,shirt,1,000000,False,warm,boho,freetime
1508,Buttons Skirt ycoo,skirt,flared_skirt,2,666633,False,warm,boho,work

--- PANTALONES 1 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
403,Lisa Shirt romb,top,shirt,3,C19A6B,False,warm_season,street,freetime
1145,Erin Jeans medium,bottoms,cigarette,2,000081,False,cold_season,casual,freetime
1889,Dots Top charlior,top,tops,3,000000,False,warm,classic,freetime

--- PANTALONES 2 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
406,Elle Tshirt cotton,top,t-shirts,3,ECE9D6,False,warm_season,casual,freetime
881,Vicky Tshirt street,top,tops,3,800000,False,warm,boho,freetime
1331,Olivia Pant vichy,bottoms,cigarette,2,000000,False,warm_season,classic,work

--- PANTALONES 3 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
600,Blake Skirt pencil,skirt,pencil,2,000000,False,warm_season,classic,work
890,Douglas Cardigan shine,top,cardigan,3,00008B,False,warm_season,classic,freetime
1233,Than Pant place,bottoms,cigarette,2,00008B,False,cold_season,casual,freetime

--- ACCESORIOS 1 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
848,Kigali Jacket denim,outerwear,cowgirl,4,FF00A8,False,cold_season,street,freetime
880,Vicky Tshirt street,top,tops,3,00008B,False,warm,boho,freetime
891,Douglas Cardigan shine,top,cardigan,3,B94600,False,warm_season,classic,freetime

--- ACCESORIOS 2 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
854,Medos Tshirt slub,top,t-shirts,3,008000,False,warm_season,casual,freetime
1770,Roxana Jacket pale,outerwear,cowgirl,4,D3D3D3,False,warm_season,street,freetime
1952,Astra Sweatshirt ward,top,hoodies,3,5F5E5E,False,warm_season,casual,freetime

--- ACCESORIOS 3 ---

,nombre_producto,categoria_prenda,subcategoria_prenda,nivel,hexadecimal,basic,weather,style,application
index,,,,,,,,,
150,Flower Scarf big,scarf,handkerchief,4,008000,False,warm,boho,freetime
582,Karla Cardigan buttons,top,cardigan,3,DEB24C,False,cold,boho,freetime
1359,Summer Shirt majolica,top,shirt,3,000000,False,warm_season,classic,work